import type { TokensFile } from '../src/types/manifest';

// ─── Flatten helpers ──────────────────────────────────────────────────────────

export interface FlatToken {
  path: string;       // dot-separated, e.g. "color.text.headline"
  cssVar: string;     // e.g. "--color-text-headline"
  value: string;      // resolved scalar value
  type: string;
}

function flattenRecursive(obj: Record<string, unknown>, prefix: string, out: FlatToken[]): void {
  for (const [key, val] of Object.entries(obj)) {
    const path = prefix ? `${prefix}.${key}` : key;
    if (val && typeof val === 'object' && '$type' in (val as object)) {
      const token = val as { $type: string; $value: unknown };
      if (token.$type === 'color' || token.$type === 'dimension') {
        out.push({
          path,
          cssVar: `--${path.replace(/\./g, '-')}`,
          value: String(token.$value),
          type: token.$type,
        });
      } else if (token.$type === 'typography') {
        const v = token.$value as Record<string, string>;
        const base = `--${path.replace(/\./g, '-')}`;
        out.push({ path: `${path}.fontFamily`,  cssVar: `${base}-font-family`,  value: v.fontFamily,  type: 'typography' });
        out.push({ path: `${path}.fontSize`,    cssVar: `${base}-font-size`,    value: v.fontSize,    type: 'typography' });
        out.push({ path: `${path}.fontWeight`,  cssVar: `${base}-font-weight`,  value: v.fontWeight,  type: 'typography' });
        out.push({ path: `${path}.lineHeight`,  cssVar: `${base}-line-height`,  value: v.lineHeight,  type: 'typography' });
      }
    } else if (val && typeof val === 'object') {
      flattenRecursive(val as Record<string, unknown>, path, out);
    }
  }
}

export function flattenTokens(tokens: TokensFile): FlatToken[] {
  const out: FlatToken[] = [];
  flattenRecursive(tokens as Record<string, unknown>, '', out);
  return out;
}

/** Map from token dot-path to its primary scalar value (for component template lookups) */
export function buildValueMap(flat: FlatToken[]): Map<string, string> {
  const map = new Map<string, string>();
  for (const t of flat) {
    // For typography, also register the base path → fontFamily as representative value
    if (!map.has(t.path)) map.set(t.path, t.value);
  }
  return map;
}

// ─── CSS output ───────────────────────────────────────────────────────────────

export function generateCSS(tokens: TokensFile): string {
  const flat = flattenTokens(tokens);
  const sections: Record<string, FlatToken[]> = {};

  for (const t of flat) {
    const group = t.path.split('.')[0];
    (sections[group] ??= []).push(t);
  }

  const lines: string[] = [
    '/* Auto-generated by DesignBridge — do not edit manually */',
    ':root {',
  ];

  for (const [group, tokens] of Object.entries(sections)) {
    lines.push(``, `  /* ${group} */`);
    for (const t of tokens) {
      lines.push(`  ${t.cssVar}: ${t.value};`);
    }
  }

  lines.push('}', '');
  return lines.join('\n');
}

// ─── TypeScript output ────────────────────────────────────────────────────────

function buildNestedObject(
  obj: Record<string, unknown>,
  path: string[],
  value: string
): void {
  let cur = obj;
  for (let i = 0; i < path.length - 1; i++) {
    cur[path[i]] ??= {};
    cur = cur[path[i]] as Record<string, unknown>;
  }
  cur[path[path.length - 1]] = value;
}

export function generateTS(tokens: TokensFile): string {
  const flat = flattenTokens(tokens);

  // Build nested object for the `tokens` constant
  const nested: Record<string, unknown> = {};
  for (const t of flat) {
    buildNestedObject(nested, t.path.split('.'), t.value);
  }

  // Build TokenPath union
  // Use only top-level token paths (not typography sub-properties)
  const topPaths = flat
    .filter((t) => t.type !== 'typography' || !t.path.includes('.font'))
    .map((t) => t.type === 'typography' ? t.path.split('.').slice(0, -1).join('.') : t.path);
  const uniquePaths = Array.from(new Set(topPaths));

  const lines = [
    '// Auto-generated by DesignBridge — do not edit manually',
    '',
    `export const tokens = ${JSON.stringify(nested, null, 2)} as const;`,
    '',
    'export type TokenPath =',
    uniquePaths.map((p) => `  | '${p}'`).join('\n') + ';',
    '',
    '/** Get the CSS variable name for a token path */',
    "export function cssVar(path: TokenPath): string {",
    "  return `var(--${path.replace(/\\./g, '-')})`;",
    '}',
    '',
  ];

  return lines.join('\n');
}
