import type { ComponentEntry, ComponentProp } from '../src/types/manifest';

// ─── Name helpers ─────────────────────────────────────────────────────────────

export function toPascalCase(str: string): string {
  return str
    .split(/[\s_\-/]+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('');
}

export function toCamelCase(str: string): string {
  const p = toPascalCase(str);
  return p.charAt(0).toLowerCase() + p.slice(1);
}

export function toFilename(componentName: string): string {
  return `${toPascalCase(componentName)}.tsx`;
}

// ─── Type generation ──────────────────────────────────────────────────────────

function enumTypeName(componentName: string, propName: string): string {
  return `${toPascalCase(componentName)}${toPascalCase(propName)}`;
}

function propTypeString(entry: ComponentEntry, prop: ComponentProp): string {
  if (prop.type === 'boolean') return 'boolean';
  if (prop.type === 'number') return 'number';
  if (prop.type === 'string') return 'string';
  return enumTypeName(entry.name, prop.name);
}

function enumDeclarations(entry: ComponentEntry): string {
  return entry.props
    .filter((p) => p.type === 'enum' && p.values.length > 0)
    .map((p) => {
      const typeName = enumTypeName(entry.name, p.name);
      const union = p.values.map((v) => `'${v}'`).join(' | ');
      return `export type ${typeName} = ${union};`;
    })
    .join('\n');
}

function interfaceDeclaration(entry: ComponentEntry, componentName: string): string {
  const lines: string[] = [];
  for (const prop of entry.props) {
    const camel = toCamelCase(prop.name);
    const type = propTypeString(entry, prop);
    lines.push(`  ${camel}?: ${type};`);
  }
  lines.push('  children?: React.ReactNode;');
  lines.push('  className?: string;');
  lines.push('  style?: React.CSSProperties;');
  return `export interface ${componentName}Props {\n${lines.join('\n')}\n}`;
}

function destructureParams(entry: ComponentEntry): string {
  const params: string[] = [];
  for (const prop of entry.props) {
    const camel = toCamelCase(prop.name);
    const def = prop.default;
    if (def !== null && def !== undefined && def !== '') {
      const defStr = typeof def === 'string' ? `'${def}'` : String(def);
      params.push(`  ${camel} = ${defStr}`);
    } else {
      params.push(`  ${camel}`);
    }
  }
  params.push('  children');
  params.push('  className');
  params.push('  style');
  return params.join(',\n');
}

// ─── Token block ──────────────────────────────────────────────────────────────

function tokenComment(entry: ComponentEntry, valueMap: Map<string, string>): string {
  if (!entry.tokenRefs.length) return '';

  const lines = ['// Design tokens used by this component:'];
  for (const ref of entry.tokenRefs) {
    const cssVar = `--${ref.replace(/\./g, '-')}`;
    const value = valueMap.get(ref) ?? '?';
    lines.push(`//   ${ref.padEnd(42)} ${value.padEnd(12)}  → var(${cssVar})`);
  }
  return lines.join('\n') + '\n';
}

function tokenStyleProp(entry: ComponentEntry, valueMap: Map<string, string>): string {
  if (!entry.tokenRefs.length) return 'style={style}';

  const colorRefs = entry.tokenRefs.filter((r) => r.startsWith('color.'));
  if (!colorRefs.length) return 'style={style}';

  const propLines = colorRefs.map((ref) => {
    const cssVar = `--${ref.replace(/\./g, '-')}`;
    const fallback = valueMap.get(ref) ?? 'inherit';
    return `        '${cssVar}': 'var(${cssVar}, ${fallback})',`;
  });

  return ['style={{', ...propLines, '        ...style,', '      }}'].join('\n');
}

// ─── Full component file ──────────────────────────────────────────────────────

export function generateComponentFile(
  entry: ComponentEntry,
  valueMap: Map<string, string>
): string {
  const componentName = toPascalCase(entry.name);
  const enumSection = enumDeclarations(entry);
  const interfaceSection = interfaceDeclaration(entry, componentName);
  const params = destructureParams(entry);
  const tokenBlock = tokenComment(entry, valueMap);
  const styleAttr = tokenStyleProp(entry, valueMap);

  return [
    `// Auto-generated by DesignBridge — do not edit manually`,
    `// Figma: ${entry.figmaUrl}`,
    `// UUID:  ${entry.uuid}`,
    ``,
    `import React from 'react';`,
    ``,
    enumSection ? enumSection + '\n' : null,
    interfaceSection,
    ``,
    tokenBlock || null,
    `export const ${componentName}: React.FC<${componentName}Props> = ({`,
    params,
    `}) => {`,
    `  return (`,
    `    <div`,
    `      className={className}`,
    `      data-component="${entry.uuid}"`,
    `      ${styleAttr}`,
    `    >`,
    `      {children}`,
    `    </div>`,
    `  );`,
    `};`,
    ``,
    `export default ${componentName};`,
    ``,
  ]
    .filter((l) => l !== null)
    .join('\n');
}
