const GROUP_ORDER = ['color', 'font', 'spacing', 'radius', 'shadow'];
const GROUP_LABEL = {
  color: 'colors', font: 'typography', spacing: 'spacing', radius: 'radius', shadow: 'shadows',
};
const LOW = '/* unsicher erkannt — bitte prüfen */';

function linesForToken(tk) {
  const flag = tk.confidence === 'low' ? ` ${LOW}` : '';
  if (tk.group === 'font') {
    return [
      `  --font-${tk.name}-size: ${tk.value.fontSize};${flag}`,
      `  --font-${tk.name}-weight: ${tk.value.fontWeight};`,
    ];
  }
  const prefix = { color: 'color', spacing: 'spacing', radius: 'radius', shadow: 'shadow' }[tk.group];
  return [`  --${prefix}-${tk.name}: ${tk.value};${flag}`];
}

export function emitCss(tokens) {
  const lines = ['/* Auto-generated by DesignBridge — do not edit manually */', ':root {'];
  for (const group of GROUP_ORDER) {
    const inGroup = tokens.filter(t => t.group === group);
    if (inGroup.length === 0) continue;
    lines.push('', `  /* ${GROUP_LABEL[group]} */`);
    for (const tk of inGroup) lines.push(...linesForToken(tk));
  }
  lines.push('}', '');
  return lines.join('\n');
}
