import { matchTemplate } from '../components/templates/registry.js';
import { LOW_CONFIDENCE_COMMENT } from '../components/templates/constants.js';
import { normalizeTokens } from './normalizeTokens.js';
import { pickTokens } from './pickTokens.js';
import { slugify } from './slugify.js';

const KINDS = [
  ['atomics', 'atomic'],
  ['components', 'component'],
  ['patterns', 'pattern'],
];

function toPascal(slug) {
  return slug
    .split('-')
    .filter(Boolean)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');
}

function genericStub(pascal, item) {
  const flag = item?.confidence === 'low' ? LOW_CONFIDENCE_COMMENT : '';
  return (
    flag +
    [
      '// Auto-generated by DesignBridge — generischer Stub, bitte ausbauen',
      `export function ${pascal}({ className = "", ...props }) {`,
      '  // TODO: Struktur dieser Komponente ergänzen (Scan liefert nur Name + Varianten)',
      '  return <div className={className} {...props} />;',
      '}',
      '',
    ].join('\n')
  );
}

export function emitComponents(result, kind) {
  const raw = result?.raw;
  if (!raw) return [];
  const picks = pickTokens(normalizeTokens(raw.tokens));
  const out = [];
  for (const [rawKey, itemKind] of KINDS) {
    if (kind && kind !== itemKind) continue;
    const items = Array.isArray(raw[rawKey]) ? raw[rawKey] : [];
    for (const item of items) {
      const tpl = matchTemplate(item.name);
      const slug = slugify(item.name) || 'component';
      const pascal = toPascal(slug) || 'Component';
      const interp = !tpl ? (result?.interpretations?.[item.name] ?? null) : null;
      const unresolved = !tpl && !interp;
      const failedListed = (result?.interpretFailed ?? []).includes(item.name);
      const lifted = Boolean(item.sourceCode);
      out.push({
        name: item.name,
        slug,
        filename: lifted && item.path ? item.path.split('/').pop() : `${pascal}.jsx`,
        kind: itemKind,
        templateKey: tpl?.key ?? null,
        variants: tpl?.variants ?? [],
        code: lifted
          ? item.sourceCode
          : (tpl ? tpl.emit(picks, item) : (interp?.jsx?.trim() ? interp.jsx : genericStub(pascal, item))),
        confidence: item.confidence ?? null,
        source: item.source ?? null,
        lifted,
        notes: item.notes ?? null,
        hasPreview: Boolean(tpl),
        interpretedHtml: interp?.html ?? null,
        interpretFailed: unresolved && failedListed,
        interpretPending: unresolved && !failedListed && Boolean(result?.interpretPending),
      });
    }
  }
  return out;
}
