import { matchTemplate } from '../components/templates/registry.js';
import { LOW_CONFIDENCE_COMMENT } from '../components/templates/constants.js';
import { normalizeTokens } from './normalizeTokens.js';
import { pickTokens } from './pickTokens.js';
import { slugify } from './slugify.js';
import { htmlToPlan } from './htmlToPlan.js';
import { planToJsx } from './planToJsx.js';

const KINDS = [
  ['atoms', 'atom'],
  ['molecules', 'molecule'],
  ['organisms', 'organism'],
  ['templates', 'template'],
];

function toPascal(slug) {
  return slug
    .split('-')
    .filter(Boolean)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');
}

function genericStub(pascal, item) {
  const flag = item?.confidence === 'low' ? LOW_CONFIDENCE_COMMENT : '';
  return (
    flag +
    [
      '// Auto-generated by DesignBridge — generischer Stub, bitte ausbauen',
      `export function ${pascal}({ className = "", ...props }) {`,
      '  // TODO: Struktur dieser Komponente ergänzen (Scan liefert nur Name + Varianten)',
      '  return <div className={className} {...props} />;',
      '}',
      '',
    ].join('\n')
  );
}

/** Code aus der KI-Interpretation ableiten (Scheibe 1, kanonischer plan → Tailwind): hat der
 *  Baustein interp.html, wird der plan deterministisch daraus gebaut (htmlToPlan, wie im Figma-
 *  Pfad) und via planToJsx zu Tailwind/JSX gegossen — DERSELBE plan wie der Figma-Export, statt
 *  Geminis separatem interp.jsx. Leeres/kaputtes html (plan === null) oder gar keine Interpretation
 *  → generischer Stub. knownComponents bewusst leer: der Code-Export braucht keine component-ref-
 *  Instanzen (die Datei ist eigenständig), planToJsx würde sie ohnehin nur als fallback rendern. */
function codeFromInterp(interp, pascal, item, namedColors) {
  const html = interp?.html;
  if (html && html.trim()) {
    const { plan } = htmlToPlan(html, { tokens: { colors: namedColors }, knownComponents: [] });
    if (plan) return planToJsx(plan, { name: pascal });
  }
  return genericStub(pascal, item);
}

export function emitComponents(result, kind) {
  const raw = result?.raw;
  if (!raw) return [];
  const picks = pickTokens(normalizeTokens(raw.tokens));
  // Dieselbe disambiguierte Farbliste wie emitFigmaComponents — htmlToPlan.matchColorToken bindet
  // per Hex und reicht .name durch (Token-Referenz im plan). Für Scheibe 1 (arbitrary values)
  // reicht der Hex, die Namen sind fürs spätere Token-Snapping (Scheibe 2) schon korrekt gesetzt.
  const normalized = normalizeTokens(raw.tokens);
  const namedColors = normalized.filter((t) => t.group === 'color').map((t) => ({ hex: t.value, name: t.name }));
  const out = [];
  for (const [rawKey, itemKind] of KINDS) {
    if (kind && kind !== itemKind) continue;
    const items = Array.isArray(raw[rawKey]) ? raw[rawKey] : [];
    for (const item of items) {
      const lifted = Boolean(item.sourceCode);
      // Gehobener Repo-Code ist maßgeblich — ein zufälliger Template-Namenstreffer
      // (z. B. "CardSkeleton" → card) darf ihn NICHT auf die generische
      // Template-Vorschau kapern und den Interpret-Knopf verstecken (FF2).
      const tpl = lifted ? null : matchTemplate(item.name);
      const slug = slugify(item.name) || 'component';
      const pascal = toPascal(slug) || 'Component';
      const interp = !tpl ? (result?.interpretations?.[item.name] ?? null) : null;
      const unresolved = !tpl && !interp;
      const failedListed = (result?.interpretFailed ?? []).includes(item.name);
      out.push({
        name: item.name,
        slug,
        filename: lifted && item.path ? item.path.split('/').pop() : `${pascal}.jsx`,
        kind: itemKind,
        templateKey: tpl?.key ?? null,
        variants: tpl?.variants ?? [],
        code: lifted
          ? item.sourceCode
          : (tpl ? tpl.emit(picks, item) : codeFromInterp(interp, pascal, item, namedColors)),
        confidence: item.confidence ?? null,
        source: item.source ?? null,
        lifted,
        notes: item.notes ?? null,
        hasPreview: Boolean(tpl),
        interpretedHtml: interp?.html ?? null,
        interpretedModel: interp?.model ?? null,
        interpretedDemo: Boolean(interp?.demo),
        interpretFailed: unresolved && failedListed,
        interpretPending: unresolved && !failedListed && Boolean(result?.interpretPending),
      });
    }
  }
  return out;
}
