// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=394-2770
// UUID:  1d74891b-7013-407a-b2eb-39dead8b4655

import React from 'react';

export interface 20.12.2019Props {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const 20.12.2019: React.FC<20.12.2019Props> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="1d74891b-7013-407a-b2eb-39dead8b4655"
      style={style}
    >
      {children}
    </div>
  );
};

export default 20.12.2019;
