// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/J7YKfOdzfZxAjJz2Mxwkze?node-id=1-513
// UUID:  6e78faae-e892-43fb-89de-a0e505a67a81

import React from 'react';

export interface AccountIconProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const AccountIcon: React.FC<AccountIconProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="6e78faae-e892-43fb-89de-a0e505a67a81"
      style={style}
    >
      {children}
    </div>
  );
};

export default AccountIcon;
