// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=359-2467
// UUID:  8e014c2b-ee93-430e-a82b-ce563c3033cd

import React from 'react';

export interface ArrowRightProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const ArrowRight: React.FC<ArrowRightProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="8e014c2b-ee93-430e-a82b-ce563c3033cd"
      style={style}
    >
      {children}
    </div>
  );
};

export default ArrowRight;
