// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/J7YKfOdzfZxAjJz2Mxwkze?node-id=1-550
// UUID:  3d0b0b0d-bdd8-4c24-b5f1-9c05dc47e58c

import React from 'react';

export interface ArrowLeftProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const ArrowLeft: React.FC<ArrowLeftProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="3d0b0b0d-bdd8-4c24-b5f1-9c05dc47e58c"
      style={style}
    >
      {children}
    </div>
  );
};

export default ArrowLeft;
