// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=359-2471
// UUID:  bb8cc685-1b0a-40d3-8a6f-5d00e4858eed

import React from 'react';

export interface ArrowDownProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const ArrowDown: React.FC<ArrowDownProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="bb8cc685-1b0a-40d3-8a6f-5d00e4858eed"
      style={style}
    >
      {children}
    </div>
  );
};

export default ArrowDown;
