// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/J7YKfOdzfZxAjJz2Mxwkze?node-id=1-545
// UUID:  70e5d949-ae55-4747-82fc-61287514aace

import React from 'react';

export interface ArrowRightProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const ArrowRight: React.FC<ArrowRightProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="70e5d949-ae55-4747-82fc-61287514aace"
      style={style}
    >
      {children}
    </div>
  );
};

export default ArrowRight;
