// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=765-144
// UUID:  07814b28-3c8f-48f6-b330-bc67107ebbae

import React from 'react';

export interface BarBottomWarenkorbMengeProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.taupe-hell                           #E5E3E3       → var(--color-taupe-hell)
//   color.new                                  #C8B677       → var(--color-new)
//   typography.h4-20pt                         ?             → var(--typography-h4-20pt)
//   typography.button-14-pt                    ?             → var(--typography-button-14-pt)

export const BarBottomWarenkorbMenge: React.FC<BarBottomWarenkorbMengeProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="07814b28-3c8f-48f6-b330-bc67107ebbae"
      style={{
        '--color-taupe-hell': 'var(--color-taupe-hell, #E5E3E3)',
        '--color-new': 'var(--color-new, #C8B677)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default BarBottomWarenkorbMenge;
