// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=801-264
// UUID:  10bfdc5c-8a77-4fad-a6d3-30c739e72bce

import React from 'react';

export interface BarBottomWarenkorbMengeMenuProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.taupe-hell                           #E5E3E3       → var(--color-taupe-hell)
//   color.new                                  #C8B677       → var(--color-new)
//   typography.h4-20pt                         ?             → var(--typography-h4-20pt)
//   typography.button-14-pt                    ?             → var(--typography-button-14-pt)

export const BarBottomWarenkorbMengeMenu: React.FC<BarBottomWarenkorbMengeMenuProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="10bfdc5c-8a77-4fad-a6d3-30c739e72bce"
      style={{
        '--color-taupe-hell': 'var(--color-taupe-hell, #E5E3E3)',
        '--color-new': 'var(--color-new, #C8B677)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default BarBottomWarenkorbMengeMenu;
