// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=55-422
// UUID:  64edc220-4136-46ff-ad7a-87fa6828dfdd

import React from 'react';

export interface BarTopIosProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const BarTopIos: React.FC<BarTopIosProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="64edc220-4136-46ff-ad7a-87fa6828dfdd"
      style={style}
    >
      {children}
    </div>
  );
};

export default BarTopIos;
