// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=1657-82
// UUID:  ca974188-7c9f-443f-881e-2d26083807b6

import React from 'react';

export interface BrowserbarCollapsedProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.white                                #FFFFFF       → var(--color-white)

export const BrowserbarCollapsed: React.FC<BrowserbarCollapsedProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="ca974188-7c9f-443f-881e-2d26083807b6"
      style={{
        '--color-white': 'var(--color-white, #FFFFFF)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default BrowserbarCollapsed;
