// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/J7YKfOdzfZxAjJz2Mxwkze?node-id=1-531
// UUID:  9fa5b9ed-2b8e-4002-b245-30ffdc9da5d4

import React from 'react';

export interface ButtonProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const Button: React.FC<ButtonProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="9fa5b9ed-2b8e-4002-b245-30ffdc9da5d4"
      style={style}
    >
      {children}
    </div>
  );
};

export default Button;
