// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=53-385
// UUID:  7e6009a1-9222-4b0a-b3a2-a86d552f7fe8

import React from 'react';

export interface ButtonTextExpand3Props {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.green                                #5C7D7D       → var(--color-green)
//   typography.body-14pt.bold                  ?             → var(--typography-body-14pt-bold)

export const ButtonTextExpand3: React.FC<ButtonTextExpand3Props> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="7e6009a1-9222-4b0a-b3a2-a86d552f7fe8"
      style={{
        '--color-green': 'var(--color-green, #5C7D7D)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default ButtonTextExpand3;
