// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=53-383
// UUID:  43c889a5-97f2-4082-8b74-9b458c9d652c

import React from 'react';

export interface ButtonTextExpand2Props {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.green                                #5C7D7D       → var(--color-green)
//   typography.body-14pt.bold                  ?             → var(--typography-body-14pt-bold)

export const ButtonTextExpand2: React.FC<ButtonTextExpand2Props> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="43c889a5-97f2-4082-8b74-9b458c9d652c"
      style={{
        '--color-green': 'var(--color-green, #5C7D7D)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default ButtonTextExpand2;
