// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=53-233
// UUID:  135850d2-4fad-41a5-b66f-52cbbabcbb53

import React from 'react';

export interface ButtonTextExpand1Props {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.green                                #5C7D7D       → var(--color-green)
//   typography.body-14pt.strikethrough         ?             → var(--typography-body-14pt-strikethrough)

export const ButtonTextExpand1: React.FC<ButtonTextExpand1Props> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="135850d2-4fad-41a5-b66f-52cbbabcbb53"
      style={{
        '--color-green': 'var(--color-green, #5C7D7D)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default ButtonTextExpand1;
