// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/J7YKfOdzfZxAjJz2Mxwkze?node-id=1-536
// UUID:  adef9cee-5a7f-4208-aaa1-c6e2a439e7e2

import React from 'react';

export interface ButtonLinkoutProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const ButtonLinkout: React.FC<ButtonLinkoutProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="adef9cee-5a7f-4208-aaa1-c6e2a439e7e2"
      style={style}
    >
      {children}
    </div>
  );
};

export default ButtonLinkout;
