// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/J7YKfOdzfZxAjJz2Mxwkze?node-id=1-505
// UUID:  4b44b8ac-8556-4690-b412-cab59f9d502c

import React from 'react';

export interface CableIconProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const CableIcon: React.FC<CableIconProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="4b44b8ac-8556-4690-b412-cab59f9d502c"
      style={style}
    >
      {children}
    </div>
  );
};

export default CableIcon;
