// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=1523-27310
// UUID:  eac401e0-83a2-40a0-8a18-566d8aa7f7e1

import React from 'react';

export interface Carousel01Props {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.white                                #FFFFFF       → var(--color-white)
//   color.grey                                 #706A6A       → var(--color-grey)

export const Carousel01: React.FC<Carousel01Props> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="eac401e0-83a2-40a0-8a18-566d8aa7f7e1"
      style={{
        '--color-white': 'var(--color-white, #FFFFFF)',
        '--color-grey': 'var(--color-grey, #706A6A)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default Carousel01;
