// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=52-139
// UUID:  35ac40a1-6e33-4bf1-b8f8-6efc4e17c4d3

import React from 'react';

export interface CarouselProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.grey                                 #706A6A       → var(--color-grey)

export const Carousel: React.FC<CarouselProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="35ac40a1-6e33-4bf1-b8f8-6efc4e17c4d3"
      style={{
        '--color-grey': 'var(--color-grey, #706A6A)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default Carousel;
