// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=1523-27531
// UUID:  d184e5aa-5044-49c7-8abf-73f37b373f89

import React from 'react';

export interface CarouselHorProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.grey                                 #706A6A       → var(--color-grey)

export const CarouselHor: React.FC<CarouselHorProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="d184e5aa-5044-49c7-8abf-73f37b373f89"
      style={{
        '--color-grey': 'var(--color-grey, #706A6A)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default CarouselHor;
