// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/J7YKfOdzfZxAjJz2Mxwkze?node-id=1-511
// UUID:  3660a919-a44e-4443-81aa-e1d8bb3bfdad

import React from 'react';

export interface ChartIconProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const ChartIcon: React.FC<ChartIconProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="3660a919-a44e-4443-81aa-e1d8bb3bfdad"
      style={style}
    >
      {children}
    </div>
  );
};

export default ChartIcon;
