// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/J7YKfOdzfZxAjJz2Mxwkze?node-id=1-507
// UUID:  38c2f683-98d6-42e8-99e7-5d08ba901a4b

import React from 'react';

export interface CheckIconProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const CheckIcon: React.FC<CheckIconProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="38c2f683-98d6-42e8-99e7-5d08ba901a4b"
      style={style}
    >
      {children}
    </div>
  );
};

export default CheckIcon;
