// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/J7YKfOdzfZxAjJz2Mxwkze?node-id=1-509
// UUID:  1d23fd1c-c450-4108-b7b5-d92bc6d66bc8

import React from 'react';

export interface CloseIconProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const CloseIcon: React.FC<CloseIconProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="1d23fd1c-c450-4108-b7b5-d92bc6d66bc8"
      style={style}
    >
      {children}
    </div>
  );
};

export default CloseIcon;
