// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=792-8869
// UUID:  586aa1e0-5a71-40f5-b676-cdb52ce3c821

import React from 'react';

export interface Component2Props {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.white                                #FFFFFF       → var(--color-white)
//   color.grey                                 #706A6A       → var(--color-grey)
//   color.turquoise-green                      #33C096       → var(--color-turquoise-green)

export const Component2: React.FC<Component2Props> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="586aa1e0-5a71-40f5-b676-cdb52ce3c821"
      style={{
        '--color-white': 'var(--color-white, #FFFFFF)',
        '--color-grey': 'var(--color-grey, #706A6A)',
        '--color-turquoise-green': 'var(--color-turquoise-green, #33C096)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default Component2;
