// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=1758-22862
// UUID:  d3c7b5f5-6209-41be-8ea4-9a8fad2ac6c7

import React from 'react';

export interface Component1Props {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.medium-green                         #859D9D       → var(--color-medium-green)
//   color.white                                #FFFFFF       → var(--color-white)

export const Component1: React.FC<Component1Props> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="d3c7b5f5-6209-41be-8ea4-9a8fad2ac6c7"
      style={{
        '--color-medium-green': 'var(--color-medium-green, #859D9D)',
        '--color-white': 'var(--color-white, #FFFFFF)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default Component1;
