// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=1523-27490
// UUID:  530c1df6-0e4d-497e-a6d0-69d35e28ff25

import React from 'react';

export interface ControlsArrowDesktopProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.grey                                 #706A6A       → var(--color-grey)

export const ControlsArrowDesktop: React.FC<ControlsArrowDesktopProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="530c1df6-0e4d-497e-a6d0-69d35e28ff25"
      style={{
        '--color-grey': 'var(--color-grey, #706A6A)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default ControlsArrowDesktop;
