// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=1057-16456
// UUID:  fc6739cb-d2fb-457f-913a-72b26b348809

import React from 'react';

export interface CrueltyFreeProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const CrueltyFree: React.FC<CrueltyFreeProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="fc6739cb-d2fb-457f-913a-72b26b348809"
      style={style}
    >
      {children}
    </div>
  );
};

export default CrueltyFree;
