// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=425-7944
// UUID:  d21f97b5-9e2c-4542-8d53-fc98376512ff

import React from 'react';

export interface CtaAnmeldenProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.new                                  #C8B677       → var(--color-new)
//   typography.h4-20pt                         ?             → var(--typography-h4-20pt)

export const CtaAnmelden: React.FC<CtaAnmeldenProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="d21f97b5-9e2c-4542-8d53-fc98376512ff"
      style={{
        '--color-new': 'var(--color-new, #C8B677)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default CtaAnmelden;
