// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=1355-30801
// UUID:  fdac9c49-2e4f-46d6-a5ea-2a516f03171f

import React from 'react';

export interface CTAConfigProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.white                                #FFFFFF       → var(--color-white)
//   color.new                                  #C8B677       → var(--color-new)

export const CTAConfig: React.FC<CTAConfigProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="fdac9c49-2e4f-46d6-a5ea-2a516f03171f"
      style={{
        '--color-white': 'var(--color-white, #FFFFFF)',
        '--color-new': 'var(--color-new, #C8B677)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default CTAConfig;
