// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=49-220
// UUID:  7aee69b0-451d-42f1-ab10-ea4a05cb3921

import React from 'react';

export interface CtaCheckoutProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.new                                  #C8B677       → var(--color-new)
//   typography.button-14-pt                    ?             → var(--typography-button-14-pt)

export const CtaCheckout: React.FC<CtaCheckoutProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="7aee69b0-451d-42f1-ab10-ea4a05cb3921"
      style={{
        '--color-new': 'var(--color-new, #C8B677)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default CtaCheckout;
