// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=55-271
// UUID:  06db3f64-3f98-44ac-83d3-09de804fad28

import React from 'react';

export interface CtaPrimaryProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.new                                  #C8B677       → var(--color-new)
//   typography.h4-20pt                         ?             → var(--typography-h4-20pt)

export const CtaPrimary: React.FC<CtaPrimaryProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="06db3f64-3f98-44ac-83d3-09de804fad28"
      style={{
        '--color-new': 'var(--color-new, #C8B677)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default CtaPrimary;
