// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=1057-16467
// UUID:  0b73f031-f3cf-45ac-89d7-28ff4056e0d7

import React from 'react';

export interface DIYProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const DIY: React.FC<DIYProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="0b73f031-f3cf-45ac-89d7-28ff4056e0d7"
      style={style}
    >
      {children}
    </div>
  );
};

export default DIY;
