// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/J7YKfOdzfZxAjJz2Mxwkze?node-id=1-515
// UUID:  cd80992c-b6e3-4adc-ad59-4b3668bd948a

import React from 'react';

export interface EarthIconProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const EarthIcon: React.FC<EarthIconProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="cd80992c-b6e3-4adc-ad59-4b3668bd948a"
      style={style}
    >
      {children}
    </div>
  );
};

export default EarthIcon;
