// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=1057-16461
// UUID:  7b93e587-901d-4d45-9ac9-50ef60a819cf

import React from 'react';

export interface FairX26SozialProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const FairX26Sozial: React.FC<FairX26SozialProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="7b93e587-901d-4d45-9ac9-50ef60a819cf"
      style={style}
    >
      {children}
    </div>
  );
};

export default FairX26Sozial;
