// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/J7YKfOdzfZxAjJz2Mxwkze?node-id=1-642
// UUID:  ee505492-7ac4-4be4-b325-cd95c1e98cbe

import React from 'react';

export interface FeaturesCarouselV1Props {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const FeaturesCarouselV1: React.FC<FeaturesCarouselV1Props> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="ee505492-7ac4-4be4-b325-cd95c1e98cbe"
      style={style}
    >
      {children}
    </div>
  );
};

export default FeaturesCarouselV1;
