// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=1197-20725
// UUID:  1fe5620d-965e-4d89-9ed9-6b180166946a

import React from 'react';

export interface FOOTERDeskktop1920Props {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.green                                #5C7D7D       → var(--color-green)
//   color.colors.white                         ?             → var(--color-colors-white)
//   typography.h5-20pt                         ?             → var(--typography-h5-20pt)
//   typography.body-14pt.regular               ?             → var(--typography-body-14pt-regular)
//   typography.text.small                      ?             → var(--typography-text-small)
//   color.white                                #FFFFFF       → var(--color-white)

export const FOOTERDeskktop1920: React.FC<FOOTERDeskktop1920Props> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="1fe5620d-965e-4d89-9ed9-6b180166946a"
      style={{
        '--color-green': 'var(--color-green, #5C7D7D)',
        '--color-colors-white': 'var(--color-colors-white, inherit)',
        '--color-white': 'var(--color-white, #FFFFFF)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default FOOTERDeskktop1920;
