// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=785-7169
// UUID:  3184d78b-152b-498b-a255-45d54f992668

import React from 'react';

export interface FOOTERDesktopProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.green                                #5C7D7D       → var(--color-green)

export const FOOTERDesktop: React.FC<FOOTERDesktopProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="3184d78b-152b-498b-a255-45d54f992668"
      style={{
        '--color-green': 'var(--color-green, #5C7D7D)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default FOOTERDesktop;
