// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=1057-16458
// UUID:  948027e5-5e47-4ce2-bf01-ce5686d5f9d4

import React from 'react';

export interface GeprüfteLieferketteProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const GeprüfteLieferkette: React.FC<GeprüfteLieferketteProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="948027e5-5e47-4ce2-bf01-ce5686d5f9d4"
      style={style}
    >
      {children}
    </div>
  );
};

export default GeprüfteLieferkette;
