// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/J7YKfOdzfZxAjJz2Mxwkze?node-id=1-517
// UUID:  187c6564-cdc3-4359-9b25-cca059664621

import React from 'react';

export interface GovernmentIconProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const GovernmentIcon: React.FC<GovernmentIconProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="187c6564-cdc3-4359-9b25-cca059664621"
      style={style}
    >
      {children}
    </div>
  );
};

export default GovernmentIcon;
