// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=1241-4
// UUID:  1d595d35-3045-4cd1-8aa6-9e7622904d66

import React from 'react';

export interface Group320Props {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.medium-green                         #859D9D       → var(--color-medium-green)
//   color.white                                #FFFFFF       → var(--color-white)

export const Group320: React.FC<Group320Props> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="1d595d35-3045-4cd1-8aa6-9e7622904d66"
      style={{
        '--color-medium-green': 'var(--color-medium-green, #859D9D)',
        '--color-white': 'var(--color-white, #FFFFFF)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default Group320;
