// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=1594-4907
// UUID:  dd82e151-dad6-494e-9b5a-7fe6fa70cef5

import React from 'react';

export interface HamburgerDesktopWhiteProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.white                                #FFFFFF       → var(--color-white)

export const HamburgerDesktopWhite: React.FC<HamburgerDesktopWhiteProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="dd82e151-dad6-494e-9b5a-7fe6fa70cef5"
      style={{
        '--color-white': 'var(--color-white, #FFFFFF)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default HamburgerDesktopWhite;
