// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=1657-263
// UUID:  83a9f97c-dc5d-4659-b7cb-48af48513b38

import React from 'react';

export interface HeaderThemaAltMobileProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.white                                #FFFFFF       → var(--color-white)
//   color.grey                                 #706A6A       → var(--color-grey)
//   color.green                                #5C7D7D       → var(--color-green)

export const HeaderThemaAltMobile: React.FC<HeaderThemaAltMobileProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="83a9f97c-dc5d-4659-b7cb-48af48513b38"
      style={{
        '--color-white': 'var(--color-white, #FFFFFF)',
        '--color-grey': 'var(--color-grey, #706A6A)',
        '--color-green': 'var(--color-green, #5C7D7D)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default HeaderThemaAltMobile;
