// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/J7YKfOdzfZxAjJz2Mxwkze?node-id=1-601
// UUID:  8f72b700-69b2-4446-99e8-1ac56701a3b8

import React from 'react';

export interface HeroImageProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const HeroImage: React.FC<HeroImageProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="8f72b700-69b2-4446-99e8-1ac56701a3b8"
      style={style}
    >
      {children}
    </div>
  );
};

export default HeroImage;
