// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=52-74
// UUID:  ba7329d3-e6dc-4ab4-a596-ad3d60825c18

import React from 'react';

export interface IconCarouselInactiveProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.grey                                 #706A6A       → var(--color-grey)

export const IconCarouselInactive: React.FC<IconCarouselInactiveProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="ba7329d3-e6dc-4ab4-a596-ad3d60825c18"
      style={{
        '--color-grey': 'var(--color-grey, #706A6A)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default IconCarouselInactive;
