// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=761-2557
// UUID:  dac6e306-8ba0-48c7-9bdb-efd9b52267bf

import React from 'react';

export interface IconWishlistInactiveProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.green                                #5C7D7D       → var(--color-green)

export const IconWishlistInactive: React.FC<IconWishlistInactiveProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="dac6e306-8ba0-48c7-9bdb-efd9b52267bf"
      style={{
        '--color-green': 'var(--color-green, #5C7D7D)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default IconWishlistInactive;
