// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=494-3397
// UUID:  03011e1c-01d3-4ba2-916c-1be6633d52a7

import React from 'react';

export interface IconWishlistSelectedProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.yellow                               #E8D286       → var(--color-yellow)

export const IconWishlistSelected: React.FC<IconWishlistSelectedProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="03011e1c-01d3-4ba2-916c-1be6633d52a7"
      style={{
        '--color-yellow': 'var(--color-yellow, #E8D286)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default IconWishlistSelected;
