// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=494-3398
// UUID:  823c0a8d-6078-4107-b772-bb2b53c07afc

import React from 'react';

export interface IconLeftProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const IconLeft: React.FC<IconLeftProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="823c0a8d-6078-4107-b772-bb2b53c07afc"
      style={style}
    >
      {children}
    </div>
  );
};

export default IconLeft;
