// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=1464-23201
// UUID:  2aac1fa2-0e17-49d5-856e-04a0ff90bee0

import React from 'react';

export interface IconShareTopProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.white                                #FFFFFF       → var(--color-white)
//   color.green                                #5C7D7D       → var(--color-green)

export const IconShareTop: React.FC<IconShareTopProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="2aac1fa2-0e17-49d5-856e-04a0ff90bee0"
      style={{
        '--color-white': 'var(--color-white, #FFFFFF)',
        '--color-green': 'var(--color-green, #5C7D7D)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default IconShareTop;
