// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=55-185
// UUID:  d4af7d25-a558-422c-9971-5b9b69fa148f

import React from 'react';

export interface IconCheckoutFilledProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.green                                #5C7D7D       → var(--color-green)

export const IconCheckoutFilled: React.FC<IconCheckoutFilledProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="d4af7d25-a558-422c-9971-5b9b69fa148f"
      style={{
        '--color-green': 'var(--color-green, #5C7D7D)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default IconCheckoutFilled;
