// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=49-38
// UUID:  b420e6f1-e18c-41a3-b98b-d871ce1cb11d

import React from 'react';

export interface IconBackProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.green                                #5C7D7D       → var(--color-green)

export const IconBack: React.FC<IconBackProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="b420e6f1-e18c-41a3-b98b-d871ce1cb11d"
      style={{
        '--color-green': 'var(--color-green, #5C7D7D)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default IconBack;
