// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=571-3555
// UUID:  03a2504f-4f34-4cfe-82ae-7b669bda7522

import React from 'react';

export interface IconSizeXSDefaultProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   typography.h6-16pt                         ?             → var(--typography-h6-16pt)

export const IconSizeXSDefault: React.FC<IconSizeXSDefaultProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="03a2504f-4f34-4cfe-82ae-7b669bda7522"
      style={style}
    >
      {children}
    </div>
  );
};

export default IconSizeXSDefault;
