// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=49-39
// UUID:  aef6b370-4dd0-42fc-8221-181beef92b1b

import React from 'react';

export interface IconMenuProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.green                                #5C7D7D       → var(--color-green)

export const IconMenu: React.FC<IconMenuProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="aef6b370-4dd0-42fc-8221-181beef92b1b"
      style={{
        '--color-green': 'var(--color-green, #5C7D7D)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default IconMenu;
