// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=883-10454
// UUID:  7e423ba1-5a0c-4f2e-b588-1b171a32e048

import React from 'react';

export interface IconGoDownProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const IconGoDown: React.FC<IconGoDownProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="7e423ba1-5a0c-4f2e-b588-1b171a32e048"
      style={style}
    >
      {children}
    </div>
  );
};

export default IconGoDown;
