// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=571-3558
// UUID:  517eeb35-c976-4b7c-a609-c63837be2d0f

import React from 'react';

export interface IconSizeLDefaultProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   typography.h6-16pt                         ?             → var(--typography-h6-16pt)

export const IconSizeLDefault: React.FC<IconSizeLDefaultProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="517eeb35-c976-4b7c-a609-c63837be2d0f"
      style={style}
    >
      {children}
    </div>
  );
};

export default IconSizeLDefault;
