// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=1504-1451
// UUID:  14eb3c29-e7d9-40af-9ddd-cf73d7920993

import React from 'react';

export interface IconWishlistActiveProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.green                                #5C7D7D       → var(--color-green)

export const IconWishlistActive: React.FC<IconWishlistActiveProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="14eb3c29-e7d9-40af-9ddd-cf73d7920993"
      style={{
        '--color-green': 'var(--color-green, #5C7D7D)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default IconWishlistActive;
