// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=494-3396
// UUID:  857a93c4-b627-4f0d-bb6a-37fe8ae68d19

import React from 'react';

export interface IconWishlistUnselectedProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.white                                #FFFFFF       → var(--color-white)
//   color.grey                                 #706A6A       → var(--color-grey)

export const IconWishlistUnselected: React.FC<IconWishlistUnselectedProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="857a93c4-b627-4f0d-bb6a-37fe8ae68d19"
      style={{
        '--color-white': 'var(--color-white, #FFFFFF)',
        '--color-grey': 'var(--color-grey, #706A6A)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default IconWishlistUnselected;
