// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=449-3361
// UUID:  81f44340-846f-46be-903a-b8464357765d

import React from 'react';

export interface IconQuantitySubtractProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.taupe-hell                           #E5E3E3       → var(--color-taupe-hell)
//   typography.h4-20pt                         ?             → var(--typography-h4-20pt)

export const IconQuantitySubtract: React.FC<IconQuantitySubtractProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="81f44340-846f-46be-903a-b8464357765d"
      style={{
        '--color-taupe-hell': 'var(--color-taupe-hell, #E5E3E3)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default IconQuantitySubtract;
