// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=571-3560
// UUID:  bd358f0d-72f0-439b-8100-a4ebcad8e368

import React from 'react';

export interface IconSizeXXLDefaultProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   typography.h6-16pt                         ?             → var(--typography-h6-16pt)

export const IconSizeXXLDefault: React.FC<IconSizeXXLDefaultProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="bd358f0d-72f0-439b-8100-a4ebcad8e368"
      style={style}
    >
      {children}
    </div>
  );
};

export default IconSizeXXLDefault;
