// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=494-3395
// UUID:  e29a89ed-b365-45b0-b55a-0614b0e7ec33

import React from 'react';

export interface IconMaximizeProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const IconMaximize: React.FC<IconMaximizeProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="e29a89ed-b365-45b0-b55a-0614b0e7ec33"
      style={style}
    >
      {children}
    </div>
  );
};

export default IconMaximize;
