// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=844-9374
// UUID:  31631661-2a6f-4efc-aeab-adbb98e99bbc

import React from 'react';

export interface IconOutlinedDirectionsChevronRightProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.black.100                            ?             → var(--color-black-100)

export const IconOutlinedDirectionsChevronRight: React.FC<IconOutlinedDirectionsChevronRightProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="31631661-2a6f-4efc-aeab-adbb98e99bbc"
      style={{
        '--color-black-100': 'var(--color-black-100, inherit)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default IconOutlinedDirectionsChevronRight;
