// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=494-3390
// UUID:  e41641c3-23d2-4445-b9a7-059759e8f773

import React from 'react';

export interface IconPauseProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const IconPause: React.FC<IconPauseProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="e41641c3-23d2-4445-b9a7-059759e8f773"
      style={style}
    >
      {children}
    </div>
  );
};

export default IconPause;
