// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=52-178
// UUID:  a3fd9ac8-44d2-46e4-9536-bde6e1d71fe2

import React from 'react';

export interface IconMerkliste12ptInactiveProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.white                                #FFFFFF       → var(--color-white)
//   color.green                                #5C7D7D       → var(--color-green)

export const IconMerkliste12ptInactive: React.FC<IconMerkliste12ptInactiveProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="a3fd9ac8-44d2-46e4-9536-bde6e1d71fe2"
      style={{
        '--color-white': 'var(--color-white, #FFFFFF)',
        '--color-green': 'var(--color-green, #5C7D7D)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default IconMerkliste12ptInactive;
