// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=1523-25297
// UUID:  a66c0e62-0e6e-4a55-b140-5bfa2ae4b3e2

import React from 'react';

export interface IconProfil12ptProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.white                                #FFFFFF       → var(--color-white)
//   color.green                                #5C7D7D       → var(--color-green)

export const IconProfil12pt: React.FC<IconProfil12ptProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="a66c0e62-0e6e-4a55-b140-5bfa2ae4b3e2"
      style={{
        '--color-white': 'var(--color-white, #FFFFFF)',
        '--color-green': 'var(--color-green, #5C7D7D)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default IconProfil12pt;
