// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=1533-643
// UUID:  b2587bf7-c2d1-4b00-9e12-ef41bc11c8eb

import React from 'react';

export interface IconBackInactiveProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.taupe-hell                           #E5E3E3       → var(--color-taupe-hell)

export const IconBackInactive: React.FC<IconBackInactiveProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="b2587bf7-c2d1-4b00-9e12-ef41bc11c8eb"
      style={{
        '--color-taupe-hell': 'var(--color-taupe-hell, #E5E3E3)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default IconBackInactive;
