// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=571-3485
// UUID:  b991d3ed-4c54-40a5-a5da-a703baf3f2f3

import React from 'react';

export interface IconSizeXLFocusProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.taupe-hell                           #E5E3E3       → var(--color-taupe-hell)
//   typography.h6-16pt                         ?             → var(--typography-h6-16pt)

export const IconSizeXLFocus: React.FC<IconSizeXLFocusProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="b991d3ed-4c54-40a5-a5da-a703baf3f2f3"
      style={{
        '--color-taupe-hell': 'var(--color-taupe-hell, #E5E3E3)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default IconSizeXLFocus;
