// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=494-3392
// UUID:  d24b311f-7216-4bd0-a41d-ce5edff14bc6

import React from 'react';

export interface IconMuteProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const IconMute: React.FC<IconMuteProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="d24b311f-7216-4bd0-a41d-ce5edff14bc6"
      style={style}
    >
      {children}
    </div>
  );
};

export default IconMute;
