// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=494-3399
// UUID:  f9f9615e-81be-49e6-a04b-7adaae733994

import React from 'react';

export interface IconRightProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const IconRight: React.FC<IconRightProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="f9f9615e-81be-49e6-a04b-7adaae733994"
      style={style}
    >
      {children}
    </div>
  );
};

export default IconRight;
