// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=591-5164
// UUID:  49db2b71-1202-442e-86c2-a93b663c6405

import React from 'react';

export interface IconCo2Props {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.taupe-medium                         #B0ACAC       → var(--color-taupe-medium)

export const IconCo2: React.FC<IconCo2Props> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="49db2b71-1202-442e-86c2-a93b663c6405"
      style={{
        '--color-taupe-medium': 'var(--color-taupe-medium, #B0ACAC)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default IconCo2;
