// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=571-3557
// UUID:  68a4b735-0713-41ca-bf18-2e13aff74693

import React from 'react';

export interface IconSizeMDefaultProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   typography.h6-16pt                         ?             → var(--typography-h6-16pt)

export const IconSizeMDefault: React.FC<IconSizeMDefaultProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="68a4b735-0713-41ca-bf18-2e13aff74693"
      style={style}
    >
      {children}
    </div>
  );
};

export default IconSizeMDefault;
