// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=494-3394
// UUID:  2794b685-d9aa-4e37-a363-10d2dbeb8364

import React from 'react';

export interface IconMinimizeProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const IconMinimize: React.FC<IconMinimizeProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="2794b685-d9aa-4e37-a363-10d2dbeb8364"
      style={style}
    >
      {children}
    </div>
  );
};

export default IconMinimize;
