// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=571-3487
// UUID:  a224b7a6-4af1-4ffa-bb29-98e48ef1ce16

import React from 'react';

export interface IconSizeSFocusProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.taupe-hell                           #E5E3E3       → var(--color-taupe-hell)
//   typography.h6-16pt                         ?             → var(--typography-h6-16pt)

export const IconSizeSFocus: React.FC<IconSizeSFocusProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="a224b7a6-4af1-4ffa-bb29-98e48ef1ce16"
      style={{
        '--color-taupe-hell': 'var(--color-taupe-hell, #E5E3E3)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default IconSizeSFocus;
