// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=1355-21674
// UUID:  c7e707b8-f3b4-424d-a91e-2f8bccb74680

import React from 'react';

export interface IconShareProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.white                                #FFFFFF       → var(--color-white)
//   color.green                                #5C7D7D       → var(--color-green)

export const IconShare: React.FC<IconShareProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="c7e707b8-f3b4-424d-a91e-2f8bccb74680"
      style={{
        '--color-white': 'var(--color-white, #FFFFFF)',
        '--color-green': 'var(--color-green, #5C7D7D)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default IconShare;
