// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=494-3391
// UUID:  4138c9a9-e502-451e-9f43-b7df054b37a1

import React from 'react';

export interface IconPlayProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const IconPlay: React.FC<IconPlayProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="4138c9a9-e502-451e-9f43-b7df054b37a1"
      style={style}
    >
      {children}
    </div>
  );
};

export default IconPlay;
