// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=754-12824
// UUID:  c5de4776-393b-49eb-9aa6-85f6c8910363

import React from 'react';

export interface IconSizeXSFocusProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.new                                  #C8B677       → var(--color-new)

export const IconSizeXSFocus: React.FC<IconSizeXSFocusProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="c5de4776-393b-49eb-9aa6-85f6c8910363"
      style={{
        '--color-new': 'var(--color-new, #C8B677)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default IconSizeXSFocus;
