// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=1523-26603
// UUID:  d7f0226e-1327-42c7-9aaf-8278c7f76af3

import React from 'react';

export interface IconWarenkorb12ptProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.white                                #FFFFFF       → var(--color-white)
//   color.green                                #5C7D7D       → var(--color-green)

export const IconWarenkorb12pt: React.FC<IconWarenkorb12ptProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="d7f0226e-1327-42c7-9aaf-8278c7f76af3"
      style={{
        '--color-white': 'var(--color-white, #FFFFFF)',
        '--color-green': 'var(--color-green, #5C7D7D)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default IconWarenkorb12pt;
