// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=761-1762
// UUID:  a5d35227-3be1-4cbc-bf34-bac7bc9fd3a5

import React from 'react';

export interface IconRückgaberechtProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.taupe-medium                         #B0ACAC       → var(--color-taupe-medium)

export const IconRückgaberecht: React.FC<IconRückgaberechtProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="a5d35227-3be1-4cbc-bf34-bac7bc9fd3a5"
      style={{
        '--color-taupe-medium': 'var(--color-taupe-medium, #B0ACAC)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default IconRückgaberecht;
