// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=52-177
// UUID:  c94546fd-33b6-49cb-9b45-85f4003429d8

import React from 'react';

export interface IconMerkliste12ptActiveProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.white                                #FFFFFF       → var(--color-white)
//   color.new                                  #C8B677       → var(--color-new)

export const IconMerkliste12ptActive: React.FC<IconMerkliste12ptActiveProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="c94546fd-33b6-49cb-9b45-85f4003429d8"
      style={{
        '--color-white': 'var(--color-white, #FFFFFF)',
        '--color-new': 'var(--color-new, #C8B677)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default IconMerkliste12ptActive;
