// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=571-3484
// UUID:  06f76030-067e-4cdd-ad81-0ed685fa7dfc

import React from 'react';

export interface IconSizeXXLFocusProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.taupe-hell                           #E5E3E3       → var(--color-taupe-hell)
//   typography.h6-16pt                         ?             → var(--typography-h6-16pt)

export const IconSizeXXLFocus: React.FC<IconSizeXXLFocusProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="06f76030-067e-4cdd-ad81-0ed685fa7dfc"
      style={{
        '--color-taupe-hell': 'var(--color-taupe-hell, #E5E3E3)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default IconSizeXXLFocus;
