// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=359-2611
// UUID:  3b6f6e23-a2b8-4fdf-a2e1-582b9d1684b1

import React from 'react';

export interface IconRessourcenschonendProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.green                                #5C7D7D       → var(--color-green)

export const IconRessourcenschonend: React.FC<IconRessourcenschonendProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="3b6f6e23-a2b8-4fdf-a2e1-582b9d1684b1"
      style={{
        '--color-green': 'var(--color-green, #5C7D7D)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default IconRessourcenschonend;
