// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=52-75
// UUID:  88bbc9a2-e561-4a75-8900-7ad586d94df3

import React from 'react';

export interface IconCarouselActiveProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.grey                                 #706A6A       → var(--color-grey)

export const IconCarouselActive: React.FC<IconCarouselActiveProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="88bbc9a2-e561-4a75-8900-7ad586d94df3"
      style={{
        '--color-grey': 'var(--color-grey, #706A6A)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default IconCarouselActive;
