// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=449-3463
// UUID:  bc116a30-97d8-4514-ad39-e6c10e428480

import React from 'react';

export interface IconCheckoutEmptyProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.green                                #5C7D7D       → var(--color-green)

export const IconCheckoutEmpty: React.FC<IconCheckoutEmptyProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="bc116a30-97d8-4514-ad39-e6c10e428480"
      style={{
        '--color-green': 'var(--color-green, #5C7D7D)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default IconCheckoutEmpty;
