// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=108-2
// UUID:  a031d4f0-ee4f-4d3f-9bb0-d5d614b0b037

import React from 'react';

export interface IconRecycleProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const IconRecycle: React.FC<IconRecycleProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="a031d4f0-ee4f-4d3f-9bb0-d5d614b0b037"
      style={style}
    >
      {children}
    </div>
  );
};

export default IconRecycle;
