// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=591-5165
// UUID:  0d96784d-e0a7-4e8f-b979-8b0bd1ec5a41

import React from 'react';

export interface IconRetoureProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.taupe-medium                         #B0ACAC       → var(--color-taupe-medium)

export const IconRetoure: React.FC<IconRetoureProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="0d96784d-e0a7-4e8f-b979-8b0bd1ec5a41"
      style={{
        '--color-taupe-medium': 'var(--color-taupe-medium, #B0ACAC)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default IconRetoure;
