// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=571-3559
// UUID:  855a45b9-aa91-4e69-ba24-2a36d4a339ee

import React from 'react';

export interface IconSizeXLDefaultProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   typography.h6-16pt                         ?             → var(--typography-h6-16pt)

export const IconSizeXLDefault: React.FC<IconSizeXLDefaultProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="855a45b9-aa91-4e69-ba24-2a36d4a339ee"
      style={style}
    >
      {children}
    </div>
  );
};

export default IconSizeXLDefault;
