// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=63-12379
// UUID:  01c8feba-453d-4dd0-8b9f-a508aa7c301a

import React from 'react';

export interface IconRatingInactiveSmallProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.taupe-hell                           #E5E3E3       → var(--color-taupe-hell)

export const IconRatingInactiveSmall: React.FC<IconRatingInactiveSmallProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="01c8feba-453d-4dd0-8b9f-a508aa7c301a"
      style={{
        '--color-taupe-hell': 'var(--color-taupe-hell, #E5E3E3)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default IconRatingInactiveSmall;
