// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=1464-23215
// UUID:  b56528d5-cff6-442f-8665-1f6309aa901d

import React from 'react';

export interface IconDoneProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.white                                #FFFFFF       → var(--color-white)
//   color.grey                                 #706A6A       → var(--color-grey)
//   color.new                                  #C8B677       → var(--color-new)

export const IconDone: React.FC<IconDoneProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="b56528d5-cff6-442f-8665-1f6309aa901d"
      style={{
        '--color-white': 'var(--color-white, #FFFFFF)',
        '--color-grey': 'var(--color-grey, #706A6A)',
        '--color-new': 'var(--color-new, #C8B677)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default IconDone;
