// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=1342-22257
// UUID:  01f7c377-1a93-45e7-a54c-6603c1854343

import React from 'react';

export interface IconAnmeldenProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.green                                #5C7D7D       → var(--color-green)

export const IconAnmelden: React.FC<IconAnmeldenProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="01f7c377-1a93-45e7-a54c-6603c1854343"
      style={{
        '--color-green': 'var(--color-green, #5C7D7D)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default IconAnmelden;
