// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=449-3360
// UUID:  eadca767-ac18-46f8-87f5-dc258f1295a6

import React from 'react';

export interface IconQuantityAddProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.taupe-hell                           #E5E3E3       → var(--color-taupe-hell)
//   typography.h4-20pt                         ?             → var(--typography-h4-20pt)

export const IconQuantityAdd: React.FC<IconQuantityAddProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="eadca767-ac18-46f8-87f5-dc258f1295a6"
      style={{
        '--color-taupe-hell': 'var(--color-taupe-hell, #E5E3E3)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default IconQuantityAdd;
