// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=1523-28197
// UUID:  d322c503-6680-4b10-84c4-1f7e27a8f39f

import React from 'react';

export interface IconCloseProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.green                                #5C7D7D       → var(--color-green)

export const IconClose: React.FC<IconCloseProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="d322c503-6680-4b10-84c4-1f7e27a8f39f"
      style={{
        '--color-green': 'var(--color-green, #5C7D7D)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default IconClose;
