// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=53-312
// UUID:  1a389a29-e4f3-46d3-9608-6b1eb5ea1dc5

import React from 'react';

export interface IconVeganProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.green                                #5C7D7D       → var(--color-green)

export const IconVegan: React.FC<IconVeganProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="1a389a29-e4f3-46d3-9608-6b1eb5ea1dc5"
      style={{
        '--color-green': 'var(--color-green, #5C7D7D)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default IconVegan;
