// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=449-3359
// UUID:  de548bcc-b21f-4e9e-94e2-8cb5d07b0283

import React from 'react';

export interface IconQuantityAmountProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.new                                  #C8B677       → var(--color-new)
//   typography.h4-20pt                         ?             → var(--typography-h4-20pt)

export const IconQuantityAmount: React.FC<IconQuantityAmountProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="de548bcc-b21f-4e9e-94e2-8cb5d07b0283"
      style={{
        '--color-new': 'var(--color-new, #C8B677)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default IconQuantityAmount;
