// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=571-3462
// UUID:  12177c29-0603-49d3-aac1-41d39e69a020

import React from 'react';

export interface IconSizeMFocusProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.taupe-hell                           #E5E3E3       → var(--color-taupe-hell)
//   typography.h6-16pt                         ?             → var(--typography-h6-16pt)

export const IconSizeMFocus: React.FC<IconSizeMFocusProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="12177c29-0603-49d3-aac1-41d39e69a020"
      style={{
        '--color-taupe-hell': 'var(--color-taupe-hell, #E5E3E3)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default IconSizeMFocus;
