// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=359-2605
// UUID:  aab1de9f-3f84-4387-a596-1a06d1d565fd

import React from 'react';

export interface IconSchadstoffreduziertProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.green                                #5C7D7D       → var(--color-green)

export const IconSchadstoffreduziert: React.FC<IconSchadstoffreduziertProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="aab1de9f-3f84-4387-a596-1a06d1d565fd"
      style={{
        '--color-green': 'var(--color-green, #5C7D7D)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default IconSchadstoffreduziert;
