// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=494-3393
// UUID:  c6bf6ef4-eeec-4044-9e9b-3dea99960408

import React from 'react';

export interface IconNotMutedProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const IconNotMuted: React.FC<IconNotMutedProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="c6bf6ef4-eeec-4044-9e9b-3dea99960408"
      style={style}
    >
      {children}
    </div>
  );
};

export default IconNotMuted;
