// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=571-3556
// UUID:  40633d51-a39e-4f94-8731-b2a8e0ffe91a

import React from 'react';

export interface IconSizeSDefaultProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   typography.h6-16pt                         ?             → var(--typography-h6-16pt)

export const IconSizeSDefault: React.FC<IconSizeSDefaultProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="40633d51-a39e-4f94-8731-b2a8e0ffe91a"
      style={style}
    >
      {children}
    </div>
  );
};

export default IconSizeSDefault;
