// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=1218-20571
// UUID:  01ae262f-20e6-4d3d-89ca-e27e5b043867

import React from 'react';

export interface IconMailProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.white                                #FFFFFF       → var(--color-white)
//   color.grey                                 #706A6A       → var(--color-grey)
//   color.green                                #5C7D7D       → var(--color-green)

export const IconMail: React.FC<IconMailProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="01ae262f-20e6-4d3d-89ca-e27e5b043867"
      style={{
        '--color-white': 'var(--color-white, #FFFFFF)',
        '--color-grey': 'var(--color-grey, #706A6A)',
        '--color-green': 'var(--color-green, #5C7D7D)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default IconMail;
