// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=63-12386
// UUID:  fc43472a-4bb3-4b45-a9cd-75475c540ed2

import React from 'react';

export interface IconRatingActiveSmallProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.new                                  #C8B677       → var(--color-new)

export const IconRatingActiveSmall: React.FC<IconRatingActiveSmallProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="fc43472a-4bb3-4b45-a9cd-75475c540ed2"
      style={{
        '--color-new': 'var(--color-new, #C8B677)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default IconRatingActiveSmall;
