// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=449-3550
// UUID:  fa7c0826-2439-4c88-b479-de61368a12fe

import React from 'react';

export interface ImagesPDPDetailsImage1Props {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const ImagesPDPDetailsImage1: React.FC<ImagesPDPDetailsImage1Props> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="fa7c0826-2439-4c88-b479-de61368a12fe"
      style={style}
    >
      {children}
    </div>
  );
};

export default ImagesPDPDetailsImage1;
