// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=408-4113
// UUID:  ca7ca484-4481-49ed-a93b-05f4e7956cb1

import React from 'react';

export interface ImagesPDPDetailImage2Props {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const ImagesPDPDetailImage2: React.FC<ImagesPDPDetailImage2Props> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="ca7ca484-4481-49ed-a93b-05f4e7956cb1"
      style={style}
    >
      {children}
    </div>
  );
};

export default ImagesPDPDetailImage2;
