// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=1057-16459
// UUID:  1970f569-bca0-4a51-9031-440ca217686e

import React from 'react';

export interface KlimaschonendProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const Klimaschonend: React.FC<KlimaschonendProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="1970f569-bca0-4a51-9031-440ca217686e"
      style={style}
    >
      {children}
    </div>
  );
};

export default Klimaschonend;
