// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/J7YKfOdzfZxAjJz2Mxwkze?node-id=17-109
// UUID:  3a54479b-ece8-45a3-9fcc-f403d41a2366

import React from 'react';

export interface LogoProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const Logo: React.FC<LogoProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="3a54479b-ece8-45a3-9fcc-f403d41a2366"
      style={style}
    >
      {children}
    </div>
  );
};

export default Logo;
