// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=49-79
// UUID:  86e9c8b8-6617-44b5-b558-6139f54001b5

import React from 'react';

export interface MobileBottomMenuMenuProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.light-grey                           #F5F4F4       → var(--color-light-grey)
//   color.green                                #5C7D7D       → var(--color-green)

export const MobileBottomMenuMenu: React.FC<MobileBottomMenuMenuProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="86e9c8b8-6617-44b5-b558-6139f54001b5"
      style={{
        '--color-light-grey': 'var(--color-light-grey, #F5F4F4)',
        '--color-green': 'var(--color-green, #5C7D7D)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default MobileBottomMenuMenu;
