// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=524-6414
// UUID:  3ce62bdb-aa28-42fa-9e0a-29527bd17e9c

import React from 'react';

export interface ModuleProductinfoTwolinesClubspecialProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.taupe-medium                         #B0ACAC       → var(--color-taupe-medium)
//   typography.pricetag-14-pt.regular.strikethrough ?             → var(--typography-pricetag-14-pt-regular-strikethrough)
//   color.new                                  #C8B677       → var(--color-new)
//   typography.pricetag-20pt.bold              ?             → var(--typography-pricetag-20pt-bold)
//   color.black                                #000000       → var(--color-black)
//   typography.h4-20pt                         ?             → var(--typography-h4-20pt)
//   typography.button-10pt                     ?             → var(--typography-button-10pt)
//   typography.body-14pt.regular               ?             → var(--typography-body-14pt-regular)
//   typography.subline-2-10pt                  ?             → var(--typography-subline-2-10pt)
//   typography.mwst                            ?             → var(--typography-mwst)
//   color.green                                #5C7D7D       → var(--color-green)
//   color.taupe-hell                           #E5E3E3       → var(--color-taupe-hell)
//   color.grey                                 #706A6A       → var(--color-grey)
//   color.white                                #FFFFFF       → var(--color-white)

export const ModuleProductinfoTwolinesClubspecial: React.FC<ModuleProductinfoTwolinesClubspecialProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="3ce62bdb-aa28-42fa-9e0a-29527bd17e9c"
      style={{
        '--color-taupe-medium': 'var(--color-taupe-medium, #B0ACAC)',
        '--color-new': 'var(--color-new, #C8B677)',
        '--color-black': 'var(--color-black, #000000)',
        '--color-green': 'var(--color-green, #5C7D7D)',
        '--color-taupe-hell': 'var(--color-taupe-hell, #E5E3E3)',
        '--color-grey': 'var(--color-grey, #706A6A)',
        '--color-white': 'var(--color-white, #FFFFFF)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default ModuleProductinfoTwolinesClubspecial;
