// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=425-3109
// UUID:  de7de1d3-c5c6-4c9d-9920-63e54f3749a8

import React from 'react';

export interface ModuleSmarteErgänzungenProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.white                                #FFFFFF       → var(--color-white)
//   color.green                                #5C7D7D       → var(--color-green)
//   color.taupe-medium                         #B0ACAC       → var(--color-taupe-medium)
//   typography.pricetag-14-pt.regular.strikethrough ?             → var(--typography-pricetag-14-pt-regular-strikethrough)
//   color.new                                  #C8B677       → var(--color-new)
//   typography.pricetag-14pt.bold              ?             → var(--typography-pricetag-14pt-bold)
//   color.black                                #000000       → var(--color-black)
//   typography.subline-2-10pt                  ?             → var(--typography-subline-2-10pt)
//   typography.h5-20pt                         ?             → var(--typography-h5-20pt)

export const ModuleSmarteErgänzungen: React.FC<ModuleSmarteErgänzungenProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="de7de1d3-c5c6-4c9d-9920-63e54f3749a8"
      style={{
        '--color-white': 'var(--color-white, #FFFFFF)',
        '--color-green': 'var(--color-green, #5C7D7D)',
        '--color-taupe-medium': 'var(--color-taupe-medium, #B0ACAC)',
        '--color-new': 'var(--color-new, #C8B677)',
        '--color-black': 'var(--color-black, #000000)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default ModuleSmarteErgänzungen;
