// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=1569-24827
// UUID:  4155e8b3-e4ff-4e30-b2c3-66290443b0da

import React from 'react';

export interface ModuleSliderAktuelleThemenProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   typography.h5-20pt                         ?             → var(--typography-h5-20pt)
//   color.white                                #FFFFFF       → var(--color-white)
//   typography.h6-16pt                         ?             → var(--typography-h6-16pt)
//   typography.subline-3                       ?             → var(--typography-subline-3)
//   typography.h1-45pt                         ?             → var(--typography-h1-45pt)
//   color.new                                  #C8B677       → var(--color-new)
//   typography.button-10pt                     ?             → var(--typography-button-10pt)

export const ModuleSliderAktuelleThemen: React.FC<ModuleSliderAktuelleThemenProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="4155e8b3-e4ff-4e30-b2c3-66290443b0da"
      style={{
        '--color-white': 'var(--color-white, #FFFFFF)',
        '--color-new': 'var(--color-new, #C8B677)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default ModuleSliderAktuelleThemen;
