// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=765-632
// UUID:  0c7d073d-2f66-4728-9115-de1b945dd150

import React from 'react';

export interface ModuleProductInfoDesktopProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.new                                  #C8B677       → var(--color-new)
//   typography.button-14-pt                    ?             → var(--typography-button-14-pt)
//   typography.pricetag-20pt.bold              ?             → var(--typography-pricetag-20pt-bold)
//   color.black                                #000000       → var(--color-black)
//   typography.h4-20pt                         ?             → var(--typography-h4-20pt)
//   typography.button-10pt                     ?             → var(--typography-button-10pt)
//   color.taupe-medium                         #B0ACAC       → var(--color-taupe-medium)
//   typography.subline-2-10pt                  ?             → var(--typography-subline-2-10pt)
//   typography.h6-16pt                         ?             → var(--typography-h6-16pt)
//   color.grey                                 #706A6A       → var(--color-grey)
//   typography.pricetag-14-pt.regular.strikethrough ?             → var(--typography-pricetag-14-pt-regular-strikethrough)
//   typography.body-14pt.regular               ?             → var(--typography-body-14pt-regular)
//   typography.mwst                            ?             → var(--typography-mwst)
//   color.green                                #5C7D7D       → var(--color-green)
//   color.taupe-hell                           #E5E3E3       → var(--color-taupe-hell)

export const ModuleProductInfoDesktop: React.FC<ModuleProductInfoDesktopProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="0c7d073d-2f66-4728-9115-de1b945dd150"
      style={{
        '--color-new': 'var(--color-new, #C8B677)',
        '--color-black': 'var(--color-black, #000000)',
        '--color-taupe-medium': 'var(--color-taupe-medium, #B0ACAC)',
        '--color-grey': 'var(--color-grey, #706A6A)',
        '--color-green': 'var(--color-green, #5C7D7D)',
        '--color-taupe-hell': 'var(--color-taupe-hell, #E5E3E3)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default ModuleProductInfoDesktop;
