// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=785-7433
// UUID:  fac40ea8-eb84-4c87-9150-caac43b6ba96

import React from 'react';

export interface ModuleVideoDesktop1920Props {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.white                                #FFFFFF       → var(--color-white)
//   color.grey                                 #706A6A       → var(--color-grey)

export const ModuleVideoDesktop1920: React.FC<ModuleVideoDesktop1920Props> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="fac40ea8-eb84-4c87-9150-caac43b6ba96"
      style={{
        '--color-white': 'var(--color-white, #FFFFFF)',
        '--color-grey': 'var(--color-grey, #706A6A)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default ModuleVideoDesktop1920;
