// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=792-7401
// UUID:  83b3e47d-7f86-4585-b8a9-cc7f1f588ea2

import React from 'react';

export interface ModuleNewsletterMobileProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   typography.body-14pt.regular               ?             → var(--typography-body-14pt-regular)
//   color.new                                  #C8B677       → var(--color-new)
//   typography.h4-20pt                         ?             → var(--typography-h4-20pt)
//   color.textcolors.maintext                  #776C82       → var(--color-textcolors-maintext)
//   color.taupe-medium                         #B0ACAC       → var(--color-taupe-medium)
//   typography.footer                          ?             → var(--typography-footer)
//   color.textcolors.headers                   #30233D       → var(--color-textcolors-headers)
//   color.white                                #FFFFFF       → var(--color-white)

export const ModuleNewsletterMobile: React.FC<ModuleNewsletterMobileProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="83b3e47d-7f86-4585-b8a9-cc7f1f588ea2"
      style={{
        '--color-new': 'var(--color-new, #C8B677)',
        '--color-textcolors-maintext': 'var(--color-textcolors-maintext, #776C82)',
        '--color-taupe-medium': 'var(--color-taupe-medium, #B0ACAC)',
        '--color-textcolors-headers': 'var(--color-textcolors-headers, #30233D)',
        '--color-white': 'var(--color-white, #FFFFFF)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default ModuleNewsletterMobile;
