// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=890-105
// UUID:  690d39c3-8404-4ea7-8d7f-1ede13a02047

import React from 'react';

export interface ModuleVersprechenProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const ModuleVersprechen: React.FC<ModuleVersprechenProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="690d39c3-8404-4ea7-8d7f-1ede13a02047"
      style={style}
    >
      {children}
    </div>
  );
};

export default ModuleVersprechen;
