// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=408-1782
// UUID:  1e01ca1b-1bab-49b4-a2db-ea6fabcad4cb

import React from 'react';

export interface ModuleFOOTERMobileProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.green                                #5C7D7D       → var(--color-green)
//   color.colors.white                         ?             → var(--color-colors-white)
//   typography.h5-20pt                         ?             → var(--typography-h5-20pt)
//   typography.body-14pt.regular               ?             → var(--typography-body-14pt-regular)
//   typography.subline-2-10pt                  ?             → var(--typography-subline-2-10pt)
//   color.white                                #FFFFFF       → var(--color-white)

export const ModuleFOOTERMobile: React.FC<ModuleFOOTERMobileProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="1e01ca1b-1bab-49b4-a2db-ea6fabcad4cb"
      style={{
        '--color-green': 'var(--color-green, #5C7D7D)',
        '--color-colors-white': 'var(--color-colors-white, inherit)',
        '--color-white': 'var(--color-white, #FFFFFF)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default ModuleFOOTERMobile;
