// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=425-3124
// UUID:  d6695825-7627-458d-9b08-a644954d25ac

import React from 'react';

export interface ModuleProduktvariantenProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.new                                  #C8B677       → var(--color-new)
//   color.black                                #000000       → var(--color-black)
//   typography.subline-2-10pt                  ?             → var(--typography-subline-2-10pt)
//   typography.h6-16pt                         ?             → var(--typography-h6-16pt)
//   typography.h5-20pt                         ?             → var(--typography-h5-20pt)

export const ModuleProduktvarianten: React.FC<ModuleProduktvariantenProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="d6695825-7627-458d-9b08-a644954d25ac"
      style={{
        '--color-new': 'var(--color-new, #C8B677)',
        '--color-black': 'var(--color-black, #000000)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default ModuleProduktvarianten;
