// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=761-1795
// UUID:  02646ebc-f4ff-4a6e-9d68-ab92325f4ae5

import React from 'react';

export interface ModuleShortFactsMobileProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.grey                                 #706A6A       → var(--color-grey)
//   typography.tag-12pt                        ?             → var(--typography-tag-12pt)
//   color.light-grey                           #F5F4F4       → var(--color-light-grey)
//   typography.tag-10pt                        ?             → var(--typography-tag-10pt)

export const ModuleShortFactsMobile: React.FC<ModuleShortFactsMobileProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="02646ebc-f4ff-4a6e-9d68-ab92325f4ae5"
      style={{
        '--color-grey': 'var(--color-grey, #706A6A)',
        '--color-light-grey': 'var(--color-light-grey, #F5F4F4)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default ModuleShortFactsMobile;
