// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=785-7532
// UUID:  9ee0552f-10d4-41da-97fa-d270af776088

import React from 'react';

export interface ModuleProduktvariantenFarbeProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.new                                  #C8B677       → var(--color-new)
//   color.black                                #000000       → var(--color-black)
//   typography.subline1-18pt                   ?             → var(--typography-subline1-18pt)
//   typography.h3-24pt                         ?             → var(--typography-h3-24pt)

export const ModuleProduktvariantenFarbe: React.FC<ModuleProduktvariantenFarbeProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="9ee0552f-10d4-41da-97fa-d270af776088"
      style={{
        '--color-new': 'var(--color-new, #C8B677)',
        '--color-black': 'var(--color-black, #000000)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default ModuleProduktvariantenFarbe;
