// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=425-4887
// UUID:  2fc26b8a-1e9b-4042-9868-e620b0952bc9

import React from 'react';

export interface ModuleSmarteErgänzungenDeskjtopProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.new                                  #C8B677       → var(--color-new)
//   typography.pricetag-20pt.bold              ?             → var(--typography-pricetag-20pt-bold)
//   color.black                                #000000       → var(--color-black)
//   typography.h6-16pt                         ?             → var(--typography-h6-16pt)
//   typography.subline-2-10pt                  ?             → var(--typography-subline-2-10pt)
//   color.taupe-hell                           #E5E3E3       → var(--color-taupe-hell)
//   color.taupe-medium                         #B0ACAC       → var(--color-taupe-medium)
//   typography.pricetag-14-pt.regular.strikethrough ?             → var(--typography-pricetag-14-pt-regular-strikethrough)
//   color.yellow                               #E8D286       → var(--color-yellow)
//   color.white                                #FFFFFF       → var(--color-white)
//   color.green                                #5C7D7D       → var(--color-green)
//   typography.h5-20pt                         ?             → var(--typography-h5-20pt)

export const ModuleSmarteErgänzungenDeskjtop: React.FC<ModuleSmarteErgänzungenDeskjtopProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="2fc26b8a-1e9b-4042-9868-e620b0952bc9"
      style={{
        '--color-new': 'var(--color-new, #C8B677)',
        '--color-black': 'var(--color-black, #000000)',
        '--color-taupe-hell': 'var(--color-taupe-hell, #E5E3E3)',
        '--color-taupe-medium': 'var(--color-taupe-medium, #B0ACAC)',
        '--color-yellow': 'var(--color-yellow, #E8D286)',
        '--color-white': 'var(--color-white, #FFFFFF)',
        '--color-green': 'var(--color-green, #5C7D7D)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default ModuleSmarteErgänzungenDeskjtop;
