// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=798-5869
// UUID:  43a594f1-3ddf-4535-a4a1-3dfecef4efb3

import React from 'react';

export interface ModuleSamrteErgnäzungSingleModuleProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.new                                  #C8B677       → var(--color-new)
//   typography.pricetag-20pt.bold              ?             → var(--typography-pricetag-20pt-bold)
//   color.black                                #000000       → var(--color-black)
//   typography.h6-16pt                         ?             → var(--typography-h6-16pt)
//   typography.subline-2-10pt                  ?             → var(--typography-subline-2-10pt)
//   color.taupe-hell                           #E5E3E3       → var(--color-taupe-hell)
//   color.taupe-medium                         #B0ACAC       → var(--color-taupe-medium)
//   typography.pricetag-14-pt.regular.strikethrough ?             → var(--typography-pricetag-14-pt-regular-strikethrough)

export const ModuleSamrteErgnäzungSingleModule: React.FC<ModuleSamrteErgnäzungSingleModuleProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="43a594f1-3ddf-4535-a4a1-3dfecef4efb3"
      style={{
        '--color-new': 'var(--color-new, #C8B677)',
        '--color-black': 'var(--color-black, #000000)',
        '--color-taupe-hell': 'var(--color-taupe-hell, #E5E3E3)',
        '--color-taupe-medium': 'var(--color-taupe-medium, #B0ACAC)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default ModuleSamrteErgnäzungSingleModule;
