// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=785-7529
// UUID:  029513f3-90db-481f-9ff5-84ebcafa88f6

import React from 'react';

export interface ModuleProduktvariantenGrösseProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   typography.h3-24pt                         ?             → var(--typography-h3-24pt)
//   color.new                                  #C8B677       → var(--color-new)

export const ModuleProduktvariantenGrösse: React.FC<ModuleProduktvariantenGrösseProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="029513f3-90db-481f-9ff5-84ebcafa88f6"
      style={{
        '--color-new': 'var(--color-new, #C8B677)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default ModuleProduktvariantenGrösse;
