// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=761-1845
// UUID:  c0ac65af-ba8a-4504-b4b1-cf585c88f89e

import React from 'react';

export interface ModuleShortFactsDesktopProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.light-grey                           #F5F4F4       → var(--color-light-grey)
//   color.grey                                 #706A6A       → var(--color-grey)
//   typography.h6-16pt                         ?             → var(--typography-h6-16pt)

export const ModuleShortFactsDesktop: React.FC<ModuleShortFactsDesktopProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="c0ac65af-ba8a-4504-b4b1-cf585c88f89e"
      style={{
        '--color-light-grey': 'var(--color-light-grey, #F5F4F4)',
        '--color-grey': 'var(--color-grey, #706A6A)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default ModuleShortFactsDesktop;
