// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=1057-16460
// UUID:  061bf561-7de7-41be-a38b-2ce955599272

import React from 'react';

export interface NachhaltigeVerpackungProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const NachhaltigeVerpackung: React.FC<NachhaltigeVerpackungProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="061bf561-7de7-41be-a38b-2ce955599272"
      style={style}
    >
      {children}
    </div>
  );
};

export default NachhaltigeVerpackung;
