// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=1057-16457
// UUID:  13c2cf94-fb86-4684-85c0-5580fdc0e69e

import React from 'react';

export interface NachhaltigeAlternativeProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const NachhaltigeAlternative: React.FC<NachhaltigeAlternativeProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="13c2cf94-fb86-4684-85c0-5580fdc0e69e"
      style={style}
    >
      {children}
    </div>
  );
};

export default NachhaltigeAlternative;
