// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=1057-16452
// UUID:  3edae090-3b0b-4770-bf9f-2962f1562582

import React from 'react';

export interface NachwachsendProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const Nachwachsend: React.FC<NachwachsendProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="3edae090-3b0b-4770-bf9f-2962f1562582"
      style={style}
    >
      {children}
    </div>
  );
};

export default Nachwachsend;
