// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/J7YKfOdzfZxAjJz2Mxwkze?node-id=1-555
// UUID:  4f9428f4-8da1-4ca2-9f3c-07b360d9b9e6

import React from 'react';

export interface NavigationProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const Navigation: React.FC<NavigationProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="4f9428f4-8da1-4ca2-9f3c-07b360d9b9e6"
      style={style}
    >
      {children}
    </div>
  );
};

export default Navigation;
