// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/J7YKfOdzfZxAjJz2Mxwkze?node-id=1-567
// UUID:  6fd13418-ec7d-4e46-811a-72e16a7816a8

import React from 'react';

export interface NavigationMobileProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const NavigationMobile: React.FC<NavigationMobileProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="6fd13418-ec7d-4e46-811a-72e16a7816a8"
      style={style}
    >
      {children}
    </div>
  );
};

export default NavigationMobile;
