// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=1661-1
// UUID:  1e705a8e-0545-41e9-a81d-57727349cbec

import React from 'react';

export interface NHModulX3CollapsedProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.medium-green                         #859D9D       → var(--color-medium-green)
//   color.white                                #FFFFFF       → var(--color-white)
//   typography.footer                          ?             → var(--typography-footer)

export const NHModulX3Collapsed: React.FC<NHModulX3CollapsedProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="1e705a8e-0545-41e9-a81d-57727349cbec"
      style={{
        '--color-medium-green': 'var(--color-medium-green, #859D9D)',
        '--color-white': 'var(--color-white, #FFFFFF)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default NHModulX3Collapsed;
