// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=1661-4
// UUID:  55b847a6-e920-493d-97d0-1756226e221c

import React from 'react';

export interface NHModulX16ActiveProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.medium-green                         #859D9D       → var(--color-medium-green)
//   color.white                                #FFFFFF       → var(--color-white)
//   typography.footer                          ?             → var(--typography-footer)

export const NHModulX16Active: React.FC<NHModulX16ActiveProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="55b847a6-e920-493d-97d0-1756226e221c"
      style={{
        '--color-medium-green': 'var(--color-medium-green, #859D9D)',
        '--color-white': 'var(--color-white, #FFFFFF)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default NHModulX16Active;
