// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=1661-3
// UUID:  2e287fbd-5515-493d-aaa7-19c53e385289

import React from 'react';

export interface NHModulX16CollapsedProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.medium-green                         #859D9D       → var(--color-medium-green)
//   color.white                                #FFFFFF       → var(--color-white)
//   typography.footer                          ?             → var(--typography-footer)

export const NHModulX16Collapsed: React.FC<NHModulX16CollapsedProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="2e287fbd-5515-493d-aaa7-19c53e385289"
      style={{
        '--color-medium-green': 'var(--color-medium-green, #859D9D)',
        '--color-white': 'var(--color-white, #FFFFFF)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default NHModulX16Collapsed;
