// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=1661-2
// UUID:  6cc35b75-6873-4c6a-be71-ecae2b13e847

import React from 'react';

export interface NHModulX3ActiveProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.medium-green                         #859D9D       → var(--color-medium-green)
//   color.white                                #FFFFFF       → var(--color-white)
//   typography.footer                          ?             → var(--typography-footer)

export const NHModulX3Active: React.FC<NHModulX3ActiveProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="6cc35b75-6873-4c6a-be71-ecae2b13e847"
      style={{
        '--color-medium-green': 'var(--color-medium-green, #859D9D)',
        '--color-white': 'var(--color-white, #FFFFFF)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default NHModulX3Active;
