// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=1661-5
// UUID:  1a579fdb-a313-48dd-8dd0-b749d6d1ba31

import React from 'react';

export interface NHModulX16ExpandedProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.medium-green                         #859D9D       → var(--color-medium-green)
//   color.white                                #FFFFFF       → var(--color-white)
//   typography.footer                          ?             → var(--typography-footer)

export const NHModulX16Expanded: React.FC<NHModulX16ExpandedProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="1a579fdb-a313-48dd-8dd0-b749d6d1ba31"
      style={{
        '--color-medium-green': 'var(--color-medium-green, #859D9D)',
        '--color-white': 'var(--color-white, #FFFFFF)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default NHModulX16Expanded;
