// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/J7YKfOdzfZxAjJz2Mxwkze?node-id=1-519
// UUID:  f6d5b9d5-df8b-4879-af18-5054aa98a59d

import React from 'react';

export interface PaintIconProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const PaintIcon: React.FC<PaintIconProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="f6d5b9d5-df8b-4879-af18-5054aa98a59d"
      style={style}
    >
      {children}
    </div>
  );
};

export default PaintIcon;
