// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=1057-16451
// UUID:  e9bad3d8-4827-4e18-9b73-b991b223ce7a

import React from 'react';

export interface PlastikfreiProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const Plastikfrei: React.FC<PlastikfreiProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="e9bad3d8-4827-4e18-9b73-b991b223ce7a"
      style={style}
    >
      {children}
    </div>
  );
};

export default Plastikfrei;
