// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=801-1120
// UUID:  e8c0bb5b-0042-4725-84f7-2c12394a7626

import React from 'react';

export interface POPProductIDProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.new                                  #C8B677       → var(--color-new)
//   typography.button-10pt                     ?             → var(--typography-button-10pt)
//   color.black                                #000000       → var(--color-black)
//   typography.body-14pt.regular               ?             → var(--typography-body-14pt-regular)
//   color.taupe-hell                           #E5E3E3       → var(--color-taupe-hell)
//   color.taupe-medium                         #B0ACAC       → var(--color-taupe-medium)
//   typography.pricetag-14-pt.regular.strikethrough ?             → var(--typography-pricetag-14-pt-regular-strikethrough)
//   typography.pricetag-14pt.bold              ?             → var(--typography-pricetag-14pt-bold)
//   typography.subline-2-10pt                  ?             → var(--typography-subline-2-10pt)
//   color.white                                #FFFFFF       → var(--color-white)
//   color.grey                                 #706A6A       → var(--color-grey)

export const POPProductID: React.FC<POPProductIDProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="e8c0bb5b-0042-4725-84f7-2c12394a7626"
      style={{
        '--color-new': 'var(--color-new, #C8B677)',
        '--color-black': 'var(--color-black, #000000)',
        '--color-taupe-hell': 'var(--color-taupe-hell, #E5E3E3)',
        '--color-taupe-medium': 'var(--color-taupe-medium, #B0ACAC)',
        '--color-white': 'var(--color-white, #FFFFFF)',
        '--color-grey': 'var(--color-grey, #706A6A)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default POPProductID;
