// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=53-157
// UUID:  7081e0ee-4416-442a-8fec-0aeb01f63dd9

import React from 'react';

export interface PriceProductStrikethroughProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.taupe-medium                         #B0ACAC       → var(--color-taupe-medium)
//   typography.pricetag-16pt.regular.strikethrough ?             → var(--typography-pricetag-16pt-regular-strikethrough)

export const PriceProductStrikethrough: React.FC<PriceProductStrikethroughProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="7081e0ee-4416-442a-8fec-0aeb01f63dd9"
      style={{
        '--color-taupe-medium': 'var(--color-taupe-medium, #B0ACAC)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default PriceProductStrikethrough;
