// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=43-380
// UUID:  7286a39c-6763-4cae-bc89-89733aae0cdc

import React from 'react';

export interface PriceHeroProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.new                                  #C8B677       → var(--color-new)
//   typography.pricetag-20pt.bold              ?             → var(--typography-pricetag-20pt-bold)

export const PriceHero: React.FC<PriceHeroProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="7286a39c-6763-4cae-bc89-89733aae0cdc"
      style={{
        '--color-new': 'var(--color-new, #C8B677)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default PriceHero;
