// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=43-264
// UUID:  a790bf04-25d7-418a-aa95-c4ba48fd1aa0

import React from 'react';

export interface PriceHeroHighlightProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.new                                  #C8B677       → var(--color-new)
//   typography.pricetag-20pt.bold              ?             → var(--typography-pricetag-20pt-bold)

export const PriceHeroHighlight: React.FC<PriceHeroHighlightProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="a790bf04-25d7-418a-aa95-c4ba48fd1aa0"
      style={{
        '--color-new': 'var(--color-new, #C8B677)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default PriceHeroHighlight;
