// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=43-263
// UUID:  bc0e0e0c-3513-48ef-a384-06a40d9dfda9

import React from 'react';

export interface PriceHeroStrikethroughProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.taupe-medium                         #B0ACAC       → var(--color-taupe-medium)
//   typography.pricetag-14-pt.regular.strikethrough ?             → var(--typography-pricetag-14-pt-regular-strikethrough)

export const PriceHeroStrikethrough: React.FC<PriceHeroStrikethroughProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="bc0e0e0c-3513-48ef-a384-06a40d9dfda9"
      style={{
        '--color-taupe-medium': 'var(--color-taupe-medium, #B0ACAC)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default PriceHeroStrikethrough;
