// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=52-450
// UUID:  f9d6a686-05ba-4982-9749-8f31b5bb19ff

import React from 'react';

export interface PriceProductProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.new                                  #C8B677       → var(--color-new)
//   typography.pricetag-14pt.bold              ?             → var(--typography-pricetag-14pt-bold)

export const PriceProduct: React.FC<PriceProductProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="f9d6a686-05ba-4982-9749-8f31b5bb19ff"
      style={{
        '--color-new': 'var(--color-new, #C8B677)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default PriceProduct;
