// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=53-158
// UUID:  5201165b-9fcf-43f4-b33b-7ffe636316a2

import React from 'react';

export interface PriceProductHighlightProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.turquoise-green                      #33C096       → var(--color-turquoise-green)
//   typography.pricetag-14pt.bold              ?             → var(--typography-pricetag-14pt-bold)

export const PriceProductHighlight: React.FC<PriceProductHighlightProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="5201165b-9fcf-43f4-b33b-7ffe636316a2"
      style={{
        '--color-turquoise-green': 'var(--color-turquoise-green, #33C096)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default PriceProductHighlight;
