// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=63-14819
// UUID:  ca9b71f6-b588-401d-9004-f629d49ff7ff

import React from 'react';

export interface RatingSmallProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.new                                  #C8B677       → var(--color-new)
//   color.taupe-hell                           #E5E3E3       → var(--color-taupe-hell)

export const RatingSmall: React.FC<RatingSmallProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="ca9b71f6-b588-401d-9004-f629d49ff7ff"
      style={{
        '--color-new': 'var(--color-new, #C8B677)',
        '--color-taupe-hell': 'var(--color-taupe-hell, #E5E3E3)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default RatingSmall;
