// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=524-4960
// UUID:  d00327a5-1c16-423d-9665-765b17f753e0

import React from 'react';

export interface RatingRatingSingleCollapsedProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.black                                #000000       → var(--color-black)
//   typography.body-14pt.bold                  ?             → var(--typography-body-14pt-bold)
//   color.taupe-medium                         #B0ACAC       → var(--color-taupe-medium)
//   typography.nutzername                      ?             → var(--typography-nutzername)
//   typography.tag-10pt                        ?             → var(--typography-tag-10pt)
//   color.new                                  #C8B677       → var(--color-new)
//   color.taupe-hell                           #E5E3E3       → var(--color-taupe-hell)

export const RatingRatingSingleCollapsed: React.FC<RatingRatingSingleCollapsedProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="d00327a5-1c16-423d-9665-765b17f753e0"
      style={{
        '--color-black': 'var(--color-black, #000000)',
        '--color-taupe-medium': 'var(--color-taupe-medium, #B0ACAC)',
        '--color-new': 'var(--color-new, #C8B677)',
        '--color-taupe-hell': 'var(--color-taupe-hell, #E5E3E3)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default RatingRatingSingleCollapsed;
