// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=416-2414
// UUID:  4e882997-9c0d-4212-9bf7-97ce4f2e56b2

import React from 'react';

export interface RatingExtendedProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.green                                #5C7D7D       → var(--color-green)
//   typography.body-14pt.bold                  ?             → var(--typography-body-14pt-bold)
//   color.black                                #000000       → var(--color-black)
//   color.taupe-medium                         #B0ACAC       → var(--color-taupe-medium)
//   typography.nutzername                      ?             → var(--typography-nutzername)
//   typography.tag-10pt                        ?             → var(--typography-tag-10pt)
//   color.new                                  #C8B677       → var(--color-new)
//   color.taupe-hell                           #E5E3E3       → var(--color-taupe-hell)

export const RatingExtended: React.FC<RatingExtendedProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="4e882997-9c0d-4212-9bf7-97ce4f2e56b2"
      style={{
        '--color-green': 'var(--color-green, #5C7D7D)',
        '--color-black': 'var(--color-black, #000000)',
        '--color-taupe-medium': 'var(--color-taupe-medium, #B0ACAC)',
        '--color-new': 'var(--color-new, #C8B677)',
        '--color-taupe-hell': 'var(--color-taupe-hell, #E5E3E3)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default RatingExtended;
