// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=408-9244
// UUID:  d8fce76a-1b9b-47f9-bc73-112b8e6a505a

import React from 'react';

export interface RatingCollapsedProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.black                                #000000       → var(--color-black)
//   typography.body-14pt.bold                  ?             → var(--typography-body-14pt-bold)
//   color.taupe-medium                         #B0ACAC       → var(--color-taupe-medium)
//   typography.nutzername                      ?             → var(--typography-nutzername)
//   typography.tag-10pt                        ?             → var(--typography-tag-10pt)
//   color.new                                  #C8B677       → var(--color-new)
//   color.taupe-hell                           #E5E3E3       → var(--color-taupe-hell)
//   typography.h5-20pt                         ?             → var(--typography-h5-20pt)
//   color.green                                #5C7D7D       → var(--color-green)

export const RatingCollapsed: React.FC<RatingCollapsedProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="d8fce76a-1b9b-47f9-bc73-112b8e6a505a"
      style={{
        '--color-black': 'var(--color-black, #000000)',
        '--color-taupe-medium': 'var(--color-taupe-medium, #B0ACAC)',
        '--color-new': 'var(--color-new, #C8B677)',
        '--color-taupe-hell': 'var(--color-taupe-hell, #E5E3E3)',
        '--color-green': 'var(--color-green, #5C7D7D)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default RatingCollapsed;
