// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=1057-16454
// UUID:  0bc68e1d-bf82-4a7b-83b7-5922f1ea935a

import React from 'react';

export interface RecycledProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const Recycled: React.FC<RecycledProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="0bc68e1d-bf82-4a7b-83b7-5922f1ea935a"
      style={style}
    >
      {children}
    </div>
  );
};

export default Recycled;
