// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=1057-16455
// UUID:  ef29a13e-3f59-4de5-848a-dbd90c39b7c7

import React from 'react';

export interface RecyclebarProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const Recyclebar: React.FC<RecyclebarProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="ef29a13e-3f59-4de5-848a-dbd90c39b7c7"
      style={style}
    >
      {children}
    </div>
  );
};

export default Recyclebar;
