// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=1241-450
// UUID:  b92b1424-4a43-42ad-8f9f-d77204634ce7

import React from 'react';

export interface Red.KastenExpandedMobileProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.medium-green                         #859D9D       → var(--color-medium-green)
//   color.white                                #FFFFFF       → var(--color-white)

export const Red.KastenExpandedMobile: React.FC<Red.KastenExpandedMobileProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="b92b1424-4a43-42ad-8f9f-d77204634ce7"
      style={{
        '--color-medium-green': 'var(--color-medium-green, #859D9D)',
        '--color-white': 'var(--color-white, #FFFFFF)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default Red.KastenExpandedMobile;
