// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=1241-1828
// UUID:  f5ef84ec-654b-467c-b0af-955ea39a4fdd

import React from 'react';

export interface Red.KastenDesktopProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.medium-green                         #859D9D       → var(--color-medium-green)
//   color.new                                  #C8B677       → var(--color-new)
//   typography.button-14-pt                    ?             → var(--typography-button-14-pt)
//   color.white                                #FFFFFF       → var(--color-white)

export const Red.KastenDesktop: React.FC<Red.KastenDesktopProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="f5ef84ec-654b-467c-b0af-955ea39a4fdd"
      style={{
        '--color-medium-green': 'var(--color-medium-green, #859D9D)',
        '--color-new': 'var(--color-new, #C8B677)',
        '--color-white': 'var(--color-white, #FFFFFF)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default Red.KastenDesktop;
