// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=1355-22587
// UUID:  e40edcb7-7f81-4079-b941-3585473c2258

import React from 'react';

export interface RückgaberechtProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.grey                                 #706A6A       → var(--color-grey)

export const Rückgaberecht: React.FC<RückgaberechtProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="e40edcb7-7f81-4079-b941-3585473c2258"
      style={{
        '--color-grey': 'var(--color-grey, #706A6A)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default Rückgaberecht;
