// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=1057-16453
// UUID:  c27ede65-acc0-4124-985b-a75348a14d48

import React from 'react';

export interface SchadstofffreiProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const Schadstofffrei: React.FC<SchadstofffreiProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="c27ede65-acc0-4124-985b-a75348a14d48"
      style={style}
    >
      {children}
    </div>
  );
};

export default Schadstofffrei;
