// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/J7YKfOdzfZxAjJz2Mxwkze?node-id=1-564
// UUID:  9fde6874-c0ea-49e9-bba7-9fae3ba2226c

import React from 'react';

export interface TableItemProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

export const TableItem: React.FC<TableItemProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="9fde6874-c0ea-49e9-bba7-9fae3ba2226c"
      style={style}
    >
      {children}
    </div>
  );
};

export default TableItem;
