// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=43-173
// UUID:  e63f8884-b0b1-4554-ba54-37f065656c27

import React from 'react';

export interface TagClubspecialProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.grey                                 #706A6A       → var(--color-grey)
//   color.white                                #FFFFFF       → var(--color-white)
//   typography.button-14-pt                    ?             → var(--typography-button-14-pt)

export const TagClubspecial: React.FC<TagClubspecialProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="e63f8884-b0b1-4554-ba54-37f065656c27"
      style={{
        '--color-grey': 'var(--color-grey, #706A6A)',
        '--color-white': 'var(--color-white, #FFFFFF)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default TagClubspecial;
