// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=93-308
// UUID:  c32cc959-e32a-4469-93bd-187fcb8e26ef

import React from 'react';

export interface TagClubspecialGreyProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.white                                #FFFFFF       → var(--color-white)
//   color.grey                                 #706A6A       → var(--color-grey)
//   typography.button-14-pt                    ?             → var(--typography-button-14-pt)

export const TagClubspecialGrey: React.FC<TagClubspecialGreyProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="c32cc959-e32a-4469-93bd-187fcb8e26ef"
      style={{
        '--color-white': 'var(--color-white, #FFFFFF)',
        '--color-grey': 'var(--color-grey, #706A6A)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default TagClubspecialGrey;
