// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=43-430
// UUID:  27da5cb9-9149-4725-8ac2-a74a5b5de7f5

import React from 'react';

export interface TagClubpreisSmallProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.new                                  #C8B677       → var(--color-new)
//   typography.button-10pt                     ?             → var(--typography-button-10pt)

export const TagClubpreisSmall: React.FC<TagClubpreisSmallProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="27da5cb9-9149-4725-8ac2-a74a5b5de7f5"
      style={{
        '--color-new': 'var(--color-new, #C8B677)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default TagClubpreisSmall;
