// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=785-8800
// UUID:  fb3454d3-5556-4573-b851-532c8cfccab8

import React from 'react';

export interface TechnischeDetailsExtProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   typography.body-14pt.regular               ?             → var(--typography-body-14pt-regular)
//   typography.h5-20pt                         ?             → var(--typography-h5-20pt)

export const TechnischeDetailsExt: React.FC<TechnischeDetailsExtProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="fb3454d3-5556-4573-b851-532c8cfccab8"
      style={style}
    >
      {children}
    </div>
  );
};

export default TechnischeDetailsExt;
