// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=53-355
// UUID:  f4a18062-f59d-4d18-9479-e7e5bcfd907b

import React from 'react';

export interface TextShortFactsProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.grey                                 #706A6A       → var(--color-grey)
//   typography.tag-12pt                        ?             → var(--typography-tag-12pt)

export const TextShortFacts: React.FC<TextShortFactsProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="f4a18062-f59d-4d18-9479-e7e5bcfd907b"
      style={{
        '--color-grey': 'var(--color-grey, #706A6A)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default TextShortFacts;
