// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=394-2772
// UUID:  ae9d6031-6c55-4670-b27a-827edebfde33

import React from 'react';

export interface TextDatumProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.taupe-medium                         #B0ACAC       → var(--color-taupe-medium)
//   typography.tag-10pt                        ?             → var(--typography-tag-10pt)

export const TextDatum: React.FC<TextDatumProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="ae9d6031-6c55-4670-b27a-827edebfde33"
      style={{
        '--color-taupe-medium': 'var(--color-taupe-medium, #B0ACAC)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default TextDatum;
