// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=785-7520
// UUID:  f7c8d336-dbbc-41df-bb6e-19242ec552a3

import React from 'react';

export interface TextProduktbeschreibungProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.green                                #5C7D7D       → var(--color-green)
//   typography.body-14pt.bold                  ?             → var(--typography-body-14pt-bold)
//   color.black                                #000000       → var(--color-black)
//   typography.body-14pt.regular               ?             → var(--typography-body-14pt-regular)
//   typography.h5-20pt                         ?             → var(--typography-h5-20pt)

export const TextProduktbeschreibung: React.FC<TextProduktbeschreibungProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="f7c8d336-dbbc-41df-bb6e-19242ec552a3"
      style={{
        '--color-green': 'var(--color-green, #5C7D7D)',
        '--color-black': 'var(--color-black, #000000)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default TextProduktbeschreibung;
