// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=53-154
// UUID:  bafd658d-54bf-44aa-a096-3018adf37ae7

import React from 'react';

export interface TextProductProductDetailProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.black                                #000000       → var(--color-black)
//   typography.h3-24pt                         ?             → var(--typography-h3-24pt)

export const TextProductProductDetail: React.FC<TextProductProductDetailProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="bafd658d-54bf-44aa-a096-3018adf37ae7"
      style={{
        '--color-black': 'var(--color-black, #000000)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default TextProductProductDetail;
