// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=53-327
// UUID:  bd38a337-5e85-463a-9964-521d3416f47d

import React from 'react';

export interface TextSustainabilityTopicCombinedProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   typography.body-14pt.regular               ?             → var(--typography-body-14pt-regular)
//   color.green                                #5C7D7D       → var(--color-green)
//   typography.tag-12pt                        ?             → var(--typography-tag-12pt)

export const TextSustainabilityTopicCombined: React.FC<TextSustainabilityTopicCombinedProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="bd38a337-5e85-463a-9964-521d3416f47d"
      style={{
        '--color-green': 'var(--color-green, #5C7D7D)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default TextSustainabilityTopicCombined;
