// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=53-366
// UUID:  8e35f52e-a37f-434e-9e8e-4b0cca551f46

import React from 'react';

export interface TextHeadlineProductdescriptionProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.black                                #000000       → var(--color-black)
//   typography.h5-20pt                         ?             → var(--typography-h5-20pt)

export const TextHeadlineProductdescription: React.FC<TextHeadlineProductdescriptionProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="8e35f52e-a37f-434e-9e8e-4b0cca551f46"
      style={{
        '--color-black': 'var(--color-black, #000000)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default TextHeadlineProductdescription;
