// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=394-2328
// UUID:  f9eaae7c-9ac5-4d72-969a-12aa548b26bc

import React from 'react';

export interface TextUserProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.grey                                 #706A6A       → var(--color-grey)
//   typography.nutzername                      ?             → var(--typography-nutzername)

export const TextUser: React.FC<TextUserProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="f9eaae7c-9ac5-4d72-969a-12aa548b26bc"
      style={{
        '--color-grey': 'var(--color-grey, #706A6A)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default TextUser;
