// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=53-1
// UUID:  1addd213-3251-4f4d-9057-780332616783

import React from 'react';

export interface TextVersandinfoProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.taupe-medium                         #B0ACAC       → var(--color-taupe-medium)
//   typography.subline-2-10pt                  ?             → var(--typography-subline-2-10pt)

export const TextVersandinfo: React.FC<TextVersandinfoProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="1addd213-3251-4f4d-9057-780332616783"
      style={{
        '--color-taupe-medium': 'var(--color-taupe-medium, #B0ACAC)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default TextVersandinfo;
