// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=43-19
// UUID:  9d2abfb6-17c6-427f-8f14-c943bf24e445

import React from 'react';

export interface TextTeaserHeadlineProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.white                                #FFFFFF       → var(--color-white)
//   typography.h1-45pt                         ?             → var(--typography-h1-45pt)

export const TextTeaserHeadline: React.FC<TextTeaserHeadlineProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="9d2abfb6-17c6-427f-8f14-c943bf24e445"
      style={{
        '--color-white': 'var(--color-white, #FFFFFF)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default TextTeaserHeadline;
