// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=53-370
// UUID:  8db62f02-b2df-4af1-a5b4-c48e8e3e1f1b

import React from 'react';

export interface TextHeadlineRatingProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   typography.h5-20pt                         ?             → var(--typography-h5-20pt)

export const TextHeadlineRating: React.FC<TextHeadlineRatingProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="8db62f02-b2df-4af1-a5b4-c48e8e3e1f1b"
      style={style}
    >
      {children}
    </div>
  );
};

export default TextHeadlineRating;
