// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=93-345
// UUID:  f7282e8e-8e13-4b39-b02b-c23008a60749

import React from 'react';

export interface TextShortFacts3Props {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.grey                                 #706A6A       → var(--color-grey)
//   typography.tag-12pt                        ?             → var(--typography-tag-12pt)

export const TextShortFacts3: React.FC<TextShortFacts3Props> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="f7282e8e-8e13-4b39-b02b-c23008a60749"
      style={{
        '--color-grey': 'var(--color-grey, #706A6A)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default TextShortFacts3;
