// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=93-338
// UUID:  37838d3f-8c37-4692-a5bd-1f22f55a2d0e

import React from 'react';

export interface TextShortFacts2Props {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.grey                                 #706A6A       → var(--color-grey)
//   typography.tag-12pt                        ?             → var(--typography-tag-12pt)

export const TextShortFacts2: React.FC<TextShortFacts2Props> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="37838d3f-8c37-4692-a5bd-1f22f55a2d0e"
      style={{
        '--color-grey': 'var(--color-grey, #706A6A)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default TextShortFacts2;
