// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=43-15
// UUID:  dc0a0ee5-dc92-4fd6-a77a-b9f78a762ee8

import React from 'react';

export interface TextTeaserDateProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.white                                #FFFFFF       → var(--color-white)
//   typography.subline-4                       ?             → var(--typography-subline-4)

export const TextTeaserDate: React.FC<TextTeaserDateProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="dc0a0ee5-dc92-4fd6-a77a-b9f78a762ee8"
      style={{
        '--color-white': 'var(--color-white, #FFFFFF)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default TextTeaserDate;
