// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=53-155
// UUID:  0be1934e-b0ba-447e-b17c-8ce91b553ffa

import React from 'react';

export interface TextProductHeadlineSmallProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.black                                #000000       → var(--color-black)
//   typography.h6-16pt                         ?             → var(--typography-h6-16pt)

export const TextProductHeadlineSmall: React.FC<TextProductHeadlineSmallProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="0be1934e-b0ba-447e-b17c-8ce91b553ffa"
      style={{
        '--color-black': 'var(--color-black, #000000)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default TextProductHeadlineSmall;
