// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=43-254
// UUID:  503b7293-d695-44be-8d5d-bb7bb0155434

import React from 'react';

export interface TextProductHeadlineHeroProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.black                                #000000       → var(--color-black)
//   typography.h4-20pt                         ?             → var(--typography-h4-20pt)

export const TextProductHeadlineHero: React.FC<TextProductHeadlineHeroProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="503b7293-d695-44be-8d5d-bb7bb0155434"
      style={{
        '--color-black': 'var(--color-black, #000000)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default TextProductHeadlineHero;
