// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=55-1
// UUID:  8fae5f42-05e8-45e6-b5dc-46080775bc21

import React from 'react';

export interface TextHeadlineSmartAddsProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   typography.h5-20pt                         ?             → var(--typography-h5-20pt)

export const TextHeadlineSmartAdds: React.FC<TextHeadlineSmartAddsProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="8fae5f42-05e8-45e6-b5dc-46080775bc21"
      style={style}
    >
      {children}
    </div>
  );
};

export default TextHeadlineSmartAdds;
