// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=53-230
// UUID:  49776767-cb53-479a-b2c6-1f646427e7b3

import React from 'react';

export interface TextStoryHeadlineProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.dark-green                           #022D2C       → var(--color-dark-green)
//   typography.h2-26pt                         ?             → var(--typography-h2-26pt)

export const TextStoryHeadline: React.FC<TextStoryHeadlineProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="49776767-cb53-479a-b2c6-1f646427e7b3"
      style={{
        '--color-dark-green': 'var(--color-dark-green, #022D2C)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default TextStoryHeadline;
