// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=53-156
// UUID:  d2829cb4-02e5-4389-b371-ff672ea0511f

import React from 'react';

export interface TextProductDescriptionSmallProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.black                                #000000       → var(--color-black)
//   typography.subline-2-10pt                  ?             → var(--typography-subline-2-10pt)

export const TextProductDescriptionSmall: React.FC<TextProductDescriptionSmallProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="d2829cb4-02e5-4389-b371-ff672ea0511f"
      style={{
        '--color-black': 'var(--color-black, #000000)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default TextProductDescriptionSmall;
