// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=43-21
// UUID:  25f9585d-90b5-4711-ac59-f0499c1d76a4

import React from 'react';

export interface TextTeaserDescriptionProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.white                                #FFFFFF       → var(--color-white)
//   typography.subline1-18pt                   ?             → var(--typography-subline1-18pt)

export const TextTeaserDescription: React.FC<TextTeaserDescriptionProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="25f9585d-90b5-4711-ac59-f0499c1d76a4"
      style={{
        '--color-white': 'var(--color-white, #FFFFFF)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default TextTeaserDescription;
