// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=53-368
// UUID:  50d666d2-2594-44f9-a3c8-56f5700a4e26

import React from 'react';

export interface TextHeadlineTechnicalDetailsProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   typography.h5-20pt                         ?             → var(--typography-h5-20pt)

export const TextHeadlineTechnicalDetails: React.FC<TextHeadlineTechnicalDetailsProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="50d666d2-2594-44f9-a3c8-56f5700a4e26"
      style={style}
    >
      {children}
    </div>
  );
};

export default TextHeadlineTechnicalDetails;
