// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=53-277
// UUID:  bed304af-2fb0-4123-9c89-61c789dddf61

import React from 'react';

export interface TextSustainabilityTopicProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   typography.tag-12pt                        ?             → var(--typography-tag-12pt)

export const TextSustainabilityTopic: React.FC<TextSustainabilityTopicProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="bed304af-2fb0-4123-9c89-61c789dddf61"
      style={style}
    >
      {children}
    </div>
  );
};

export default TextSustainabilityTopic;
