// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=43-257
// UUID:  f283f780-e4f6-4214-961d-90f9d07fc95d

import React from 'react';

export interface TextProductDescriptionHeroProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.black                                #000000       → var(--color-black)
//   typography.body-14pt.regular               ?             → var(--typography-body-14pt-regular)

export const TextProductDescriptionHero: React.FC<TextProductDescriptionHeroProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="f283f780-e4f6-4214-961d-90f9d07fc95d"
      style={{
        '--color-black': 'var(--color-black, #000000)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default TextProductDescriptionHero;
