// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=43-17
// UUID:  87393d5d-446e-4f0c-b299-da5908a99dc4

import React from 'react';

export interface TextTeaserCategoryProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.white                                #FFFFFF       → var(--color-white)
//   typography.h6-16pt                         ?             → var(--typography-h6-16pt)

export const TextTeaserCategory: React.FC<TextTeaserCategoryProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="87393d5d-446e-4f0c-b299-da5908a99dc4"
      style={{
        '--color-white': 'var(--color-white, #FFFFFF)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default TextTeaserCategory;
