// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=53-228
// UUID:  5b5ba111-6f17-4072-b152-0edbcfec9aa5

import React from 'react';

export interface TextStoryCategoryProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.dark-green                           #022D2C       → var(--color-dark-green)
//   typography.tag-12pt                        ?             → var(--typography-tag-12pt)

export const TextStoryCategory: React.FC<TextStoryCategoryProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="5b5ba111-6f17-4072-b152-0edbcfec9aa5"
      style={{
        '--color-dark-green': 'var(--color-dark-green, #022D2C)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default TextStoryCategory;
