// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=53-411
// UUID:  7b70f0f0-4f84-4393-ba25-86f2bd253108

import React from 'react';

export interface TextHighlightRatingProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.black                                #000000       → var(--color-black)
//   typography.body-14pt.bold                  ?             → var(--typography-body-14pt-bold)

export const TextHighlightRating: React.FC<TextHighlightRatingProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="7b70f0f0-4f84-4393-ba25-86f2bd253108"
      style={{
        '--color-black': 'var(--color-black, #000000)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default TextHighlightRating;
