// Auto-generated by DesignBridge — do not edit manually

export const tokens = {
  "color": {
    "black": "#000000",
    "white": "#FFFFFF",
    "grey": "#706A6A",
    "dark-red": "#492035",
    "dark-green": "#022D2C",
    "turqoise": "#B8DCD7",
    "yellow": "#E8D286",
    "green": "#5C7D7D",
    "taupe-hell": "#E5E3E3",
    "light-grey": "#F5F4F4",
    "medium-red": "#6D4D5D",
    "medium-green": "#859D9D",
    "taupe-medium": "#B0ACAC",
    "turquoise-green": "#33C096",
    "new": "#C8B677",
    "textcolors": {
      "maintext": "#776C82",
      "headers": "#30233D"
    },
    "secondary-600": "#018786",
    "secondary-500": "#01A39D"
  },
  "typography": {
    "h1-45pt": {
      "fontFamily": "Raleway",
      "fontSize": "45px",
      "fontWeight": "SemiBold",
      "lineHeight": "50px"
    },
    "h3-24pt": {
      "fontFamily": "Raleway",
      "fontSize": "24px",
      "fontWeight": "SemiBold",
      "lineHeight": "28px"
    },
    "h4-20pt": {
      "fontFamily": "Raleway",
      "fontSize": "20px",
      "fontWeight": "Medium",
      "lineHeight": "25px"
    },
    "h5-20pt": {
      "fontFamily": "Raleway",
      "fontSize": "20px",
      "fontWeight": "Regular",
      "lineHeight": "24px"
    },
    "h6-16pt": {
      "fontFamily": "Raleway",
      "fontSize": "16px",
      "fontWeight": "Regular",
      "lineHeight": "20px"
    },
    "h2-26pt": {
      "fontFamily": "Raleway",
      "fontSize": "26px",
      "fontWeight": "SemiBold",
      "lineHeight": "30px"
    },
    "subline1-18pt": {
      "fontFamily": "Roboto",
      "fontSize": "18px",
      "fontWeight": "Regular",
      "lineHeight": "35px"
    },
    "subline-2-10pt": {
      "fontFamily": "Roboto",
      "fontSize": "10px",
      "fontWeight": "Regular",
      "lineHeight": "12px"
    },
    "button-14-pt": {
      "fontFamily": "Raleway",
      "fontSize": "14px",
      "fontWeight": "Medium",
      "lineHeight": "18px"
    },
    "tag-12pt": {
      "fontFamily": "Roboto",
      "fontSize": "12px",
      "fontWeight": "Medium",
      "lineHeight": "13px"
    },
    "tag-10pt": {
      "fontFamily": "Roboto",
      "fontSize": "10px",
      "fontWeight": "Medium",
      "lineHeight": "12px"
    },
    "button-i-10-pt": {
      "fontFamily": "Raleway",
      "fontSize": "10px",
      "fontWeight": "Medium",
      "lineHeight": "10px"
    },
    "button-10pt": {
      "fontFamily": "Raleway",
      "fontSize": "10px",
      "fontWeight": "Medium",
      "lineHeight": "12px"
    },
    "button-14-pt-dark": {
      "fontFamily": "Raleway",
      "fontSize": "14px",
      "fontWeight": "Medium",
      "lineHeight": "18px"
    },
    "subline-3": {
      "fontFamily": "Roboto",
      "fontSize": "12px",
      "fontWeight": "Regular",
      "lineHeight": "18px"
    },
    "subline-4": {
      "fontFamily": "Roboto",
      "fontSize": "10px",
      "fontWeight": "Bold",
      "lineHeight": "14px"
    },
    "h1-black": {
      "fontFamily": "Raleway",
      "fontSize": "45px",
      "fontWeight": "SemiBold",
      "lineHeight": "50px"
    },
    "footer": {
      "fontFamily": "Roboto",
      "fontSize": "10px",
      "fontWeight": "Regular",
      "lineHeight": "12px"
    },
    "nutzername": {
      "fontFamily": "Roboto",
      "fontSize": "10px",
      "fontWeight": "Regular",
      "lineHeight": "12px"
    },
    "bewertung": {
      "fontFamily": "Roboto",
      "fontSize": "14px",
      "fontWeight": "Bold",
      "lineHeight": "16px"
    },
    "mwst": {
      "fontFamily": "Roboto",
      "fontSize": "10px",
      "fontWeight": "Regular",
      "lineHeight": "12px"
    },
    "body-14pt": {
      "regular": {
        "fontFamily": "Roboto",
        "fontSize": "14px",
        "fontWeight": "Regular",
        "lineHeight": "20px"
      },
      "bold": {
        "fontFamily": "Roboto",
        "fontSize": "14px",
        "fontWeight": "Bold",
        "lineHeight": "16px"
      },
      "strikethrough": {
        "fontFamily": "Roboto",
        "fontSize": "14px",
        "fontWeight": "Regular",
        "lineHeight": "20px"
      }
    },
    "pricetag-20pt": {
      "regular": {
        "fontFamily": "Roboto",
        "fontSize": "20px",
        "fontWeight": "Regular",
        "lineHeight": "24px"
      },
      "bold": {
        "fontFamily": "Roboto",
        "fontSize": "20px",
        "fontWeight": "Bold",
        "lineHeight": "20px"
      }
    },
    "pricetag-14-pt": {
      "regular": {
        "strikethrough": {
          "fontFamily": "Roboto",
          "fontSize": "14px",
          "fontWeight": "Regular",
          "lineHeight": "16px"
        }
      }
    },
    "pricetag-16pt": {
      "regular": {
        "fontFamily": "Roboto",
        "fontSize": "16px",
        "fontWeight": "Regular",
        "lineHeight": "24px"
      }
    },
    "pricetag-14pt": {
      "bold": {
        "fontFamily": "Roboto",
        "fontSize": "14px",
        "fontWeight": "Bold",
        "lineHeight": "20px"
      }
    },
    "text": {
      "small": {
        "fontFamily": "Mplus 1p",
        "fontSize": "16.200000762939453px",
        "fontWeight": "Regular",
        "lineHeight": "1.63"
      }
    },
    "caption": {
      "roboto-regular": {
        "fontFamily": "Roboto",
        "fontSize": "12px",
        "fontWeight": "Regular",
        "lineHeight": "16px"
      }
    },
    "button": {
      "roboto-medium": {
        "fontFamily": "Roboto",
        "fontSize": "14px",
        "fontWeight": "Medium",
        "lineHeight": "16px"
      }
    },
    "title": {
      "small": {
        "fontFamily": "Mplus 1p",
        "fontSize": "12.600000381469727px",
        "fontWeight": "ExtraBold",
        "lineHeight": "2.08"
      }
    },
    "text-misc": {
      "nav-footer": {
        "fontFamily": "Mplus 1p Bold",
        "fontSize": "12.600000381469727px",
        "fontWeight": "Bold",
        "lineHeight": "2.23"
      },
      "nav": {
        "fontFamily": "Mplus 1p",
        "fontSize": "14.399999618530273px",
        "fontWeight": "ExtraBold",
        "lineHeight": "2.08"
      }
    },
    "headers": {
      "h6": {
        "fontFamily": "Mplus 1p",
        "fontSize": "18px",
        "fontWeight": "Medium",
        "lineHeight": "1.4"
      },
      "h3": {
        "fontFamily": "Mplus 1p",
        "fontSize": "45px",
        "fontWeight": "Medium",
        "lineHeight": "1.4"
      }
    }
  }
} as const;

export type TokenPath =
  | 'color.black'
  | 'color.white'
  | 'color.grey'
  | 'color.dark-red'
  | 'color.dark-green'
  | 'color.turqoise'
  | 'color.yellow'
  | 'color.green'
  | 'color.taupe-hell'
  | 'color.light-grey'
  | 'color.medium-red'
  | 'color.medium-green'
  | 'color.taupe-medium'
  | 'color.turquoise-green'
  | 'color.new'
  | 'color.textcolors.maintext'
  | 'color.textcolors.headers'
  | 'color.secondary-600'
  | 'color.secondary-500'
  | 'typography.h1-45pt'
  | 'typography.h3-24pt'
  | 'typography.h4-20pt'
  | 'typography.h5-20pt'
  | 'typography.h6-16pt'
  | 'typography.h2-26pt'
  | 'typography.subline1-18pt'
  | 'typography.subline-2-10pt'
  | 'typography.button-14-pt'
  | 'typography.tag-12pt'
  | 'typography.tag-10pt'
  | 'typography.button-i-10-pt'
  | 'typography.button-10pt'
  | 'typography.button-14-pt-dark'
  | 'typography.subline-3'
  | 'typography.subline-4'
  | 'typography.h1-black'
  | 'typography.footer'
  | 'typography.nutzername'
  | 'typography.bewertung'
  | 'typography.mwst'
  | 'typography.body-14pt.regular'
  | 'typography.body-14pt.bold'
  | 'typography.body-14pt.strikethrough'
  | 'typography.pricetag-20pt.regular'
  | 'typography.pricetag-20pt.bold'
  | 'typography.pricetag-14-pt.regular.strikethrough'
  | 'typography.pricetag-16pt.regular'
  | 'typography.pricetag-14pt.bold'
  | 'typography.text.small'
  | 'typography.caption.roboto-regular'
  | 'typography.button.roboto-medium'
  | 'typography.title.small'
  | 'typography.text-misc.nav-footer'
  | 'typography.text-misc.nav'
  | 'typography.headers.h6'
  | 'typography.headers.h3';

/** Get the CSS variable name for a token path */
export function cssVar(path: TokenPath): string {
  return `var(--${path.replace(/\./g, '-')})`;
}
