// Auto-generated by DesignBridge — do not edit manually

export const tokens = {} as const;

export type TokenPath =
;

/** Get the CSS variable name for a token path */
export function cssVar(path: TokenPath): string {
  return `var(--${path.replace(/\./g, '-')})`;
}
