// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=1657-78
// UUID:  ceeae91e-62ab-4be5-8433-eef7fecc5fce

import React from 'react';

export interface TopMobileThemaProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.medium-green                         #859D9D       → var(--color-medium-green)
//   color.white                                #FFFFFF       → var(--color-white)
//   color.new                                  #C8B677       → var(--color-new)
//   typography.button-10pt                     ?             → var(--typography-button-10pt)
//   color.green                                #5C7D7D       → var(--color-green)

export const TopMobileThema: React.FC<TopMobileThemaProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="ceeae91e-62ab-4be5-8433-eef7fecc5fce"
      style={{
        '--color-medium-green': 'var(--color-medium-green, #859D9D)',
        '--color-white': 'var(--color-white, #FFFFFF)',
        '--color-new': 'var(--color-new, #C8B677)',
        '--color-green': 'var(--color-green, #5C7D7D)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default TopMobileThema;
