// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=571-3629
// UUID:  9a73df64-187c-4eb1-9d09-c7776fae5889

import React from 'react';

export interface VariantenMengeProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.new                                  #C8B677       → var(--color-new)
//   typography.h4-20pt                         ?             → var(--typography-h4-20pt)
//   color.taupe-hell                           #E5E3E3       → var(--color-taupe-hell)
//   typography.h6-16pt                         ?             → var(--typography-h6-16pt)

export const VariantenMenge: React.FC<VariantenMengeProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="9a73df64-187c-4eb1-9d09-c7776fae5889"
      style={{
        '--color-new': 'var(--color-new, #C8B677)',
        '--color-taupe-hell': 'var(--color-taupe-hell, #E5E3E3)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default VariantenMenge;
