// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=801-3732
// UUID:  6a77620e-fdb3-4562-b061-26c823d9a3f3

import React from 'react';

export interface Video1920Props {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.white                                #FFFFFF       → var(--color-white)
//   color.grey                                 #706A6A       → var(--color-grey)

export const Video1920: React.FC<Video1920Props> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="6a77620e-fdb3-4562-b061-26c823d9a3f3"
      style={{
        '--color-white': 'var(--color-white, #FFFFFF)',
        '--color-grey': 'var(--color-grey, #706A6A)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default Video1920;
