// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=702-3740
// UUID:  9a1fd273-7226-4ed6-8b6f-d4e28e87e0fb

import React from 'react';

export interface Video1920wFullscreenProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.white                                #FFFFFF       → var(--color-white)
//   color.grey                                 #706A6A       → var(--color-grey)

export const Video1920wFullscreen: React.FC<Video1920wFullscreenProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="9a1fd273-7226-4ed6-8b6f-d4e28e87e0fb"
      style={{
        '--color-white': 'var(--color-white, #FFFFFF)',
        '--color-grey': 'var(--color-grey, #706A6A)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default Video1920wFullscreen;
