// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=1355-22040
// UUID:  89a317ed-5693-4f0d-ad90-be668119e6f2

import React from 'react';

export interface VideoProductInformationAverageProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.white                                #FFFFFF       → var(--color-white)
//   color.new                                  #C8B677       → var(--color-new)
//   typography.pricetag-20pt.bold              ?             → var(--typography-pricetag-20pt-bold)
//   typography.h3-24pt                         ?             → var(--typography-h3-24pt)
//   typography.body-14pt.regular               ?             → var(--typography-body-14pt-regular)
//   typography.subline-2-10pt                  ?             → var(--typography-subline-2-10pt)
//   typography.pricetag-14-pt.regular.strikethrough ?             → var(--typography-pricetag-14-pt-regular-strikethrough)
//   typography.button-10pt                     ?             → var(--typography-button-10pt)
//   color.taupe-hell                           #E5E3E3       → var(--color-taupe-hell)
//   color.grey                                 #706A6A       → var(--color-grey)
//   color.green                                #5C7D7D       → var(--color-green)

export const VideoProductInformationAverage: React.FC<VideoProductInformationAverageProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="89a317ed-5693-4f0d-ad90-be668119e6f2"
      style={{
        '--color-white': 'var(--color-white, #FFFFFF)',
        '--color-new': 'var(--color-new, #C8B677)',
        '--color-taupe-hell': 'var(--color-taupe-hell, #E5E3E3)',
        '--color-grey': 'var(--color-grey, #706A6A)',
        '--color-green': 'var(--color-green, #5C7D7D)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default VideoProductInformationAverage;
