// Auto-generated by DesignBridge — do not edit manually
// Figma: https://www.figma.com/design/Ed1ToivQVNZpD5KtGk01iF?node-id=1355-22042
// UUID:  1a97cae2-650a-4eb8-a7fb-28e4facf49e5

import React from 'react';

export interface VideoProductInformationSmallProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}

// Design tokens used by this component:
//   color.new                                  #C8B677       → var(--color-new)
//   color.white                                #FFFFFF       → var(--color-white)
//   typography.pricetag-20pt.bold              ?             → var(--typography-pricetag-20pt-bold)
//   typography.h3-24pt                         ?             → var(--typography-h3-24pt)
//   typography.subline-2-10pt                  ?             → var(--typography-subline-2-10pt)
//   color.taupe-hell                           #E5E3E3       → var(--color-taupe-hell)
//   color.green                                #5C7D7D       → var(--color-green)
//   typography.button-10pt                     ?             → var(--typography-button-10pt)

export const VideoProductInformationSmall: React.FC<VideoProductInformationSmallProps> = ({
  children,
  className,
  style
}) => {
  return (
    <div
      className={className}
      data-component="1a97cae2-650a-4eb8-a7fb-28e4facf49e5"
      style={{
        '--color-new': 'var(--color-new, #C8B677)',
        '--color-white': 'var(--color-white, #FFFFFF)',
        '--color-taupe-hell': 'var(--color-taupe-hell, #E5E3E3)',
        '--color-green': 'var(--color-green, #5C7D7D)',
        ...style,
      }}
    >
      {children}
    </div>
  );
};

export default VideoProductInformationSmall;
