const LOW = '// unsicher erkannt — bitte prüfen\n';

export const badgeTemplate = {
  key: 'badge',
  label: 'Badge',
  variants: ['default', 'secondary'],
  match: (n) => /badge|tag|chip|pill|label/.test(n),
  emit(p, item) {
    const flag = item?.confidence === 'low' ? LOW : '';
    return (
      flag +
      [
        '// Auto-generated by DesignBridge',
        'export function Badge({ variant = "default", className = "", ...props }) {',
        '  const base = "inline-flex items-center px-2 py-0.5 rounded-full text-[12px] font-[500]";',
        '  const variants = {',
        `    default: "bg-[${p.primary}] text-[${p.onPrimary}]",`,
        `    secondary: "bg-[${p.surfaceMuted}] text-[${p.text}]",`,
        '  };',
        '  return <span className={[base, variants[variant], className].join(" ")} {...props} />;',
        '}',
        '',
      ].join('\n')
    );
  },
  styleFor(variant, p) {
    const base = {
      display: 'inline-flex', alignItems: 'center', padding: '2px 8px',
      borderRadius: '9999px', fontSize: '12px', fontWeight: 500,
    };
    if (variant === 'secondary')
      return { ...base, background: p.surfaceMuted, color: p.text };
    return { ...base, background: p.primary, color: p.onPrimary };
  },
};
