import { LOW_CONFIDENCE_COMMENT as LOW } from './constants.js';
import { colorRef, textEl, box } from './planHelpers.js';

export const badgeTemplate = {
  key: 'badge',
  label: 'Badge',
  variants: ['default', 'secondary'],
  match: (n) => /badge|tag|chip|pill/.test(n),
  emit(p, item) {
    const flag = item?.confidence === 'low' ? LOW : '';
    return (
      flag +
      [
        '// Auto-generated by DesignBridge',
        'export function Badge({ variant = "default", className = "", ...props }) {',
        '  const base = "inline-flex items-center px-2 py-0.5 rounded-full text-[12px] font-[500]";',
        '  const variants = {',
        `    default: "bg-[${p.primary}] text-[${p.onPrimary}]",`,
        `    secondary: "bg-[${p.surfaceMuted}] text-[${p.text}]",`,
        '  };',
        '  return <span className={[base, variants[variant], className].join(" ")} {...props} />;',
        '}',
        '',
      ].join('\n')
    );
  },
  styleFor(variant, p) {
    const base = {
      display: 'inline-flex', alignItems: 'center', padding: '2px 8px',
      borderRadius: '9999px', fontSize: '12px', fontWeight: 500,
    };
    if (variant === 'secondary')
      return { ...base, background: p.surfaceMuted, color: p.text };
    return { ...base, background: p.primary, color: p.onPrimary };
  },
  planFor(variant, r) {
    const fill = variant === 'secondary' ? r.surfaceMuted : r.primary;
    const color = variant === 'secondary' ? r.text : r.onPrimary;
    return box({
      padding: [2, 8, 2, 8], radius: 9999, fill: colorRef(fill),
      children: [textEl('Badge', r, color, { fontSize: 12, fontWeight: 500 })],
    });
  },
};
