import { LOW_CONFIDENCE_COMMENT as LOW } from './constants.js';
import { colorRef, px, textEl, box } from './planHelpers.js';

export const buttonTemplate = {
  key: 'button',
  label: 'Button',
  variants: ['primary', 'secondary', 'ghost'],
  match: (n) => /butt|btn|cta/.test(n),
  emit(p, item) {
    const flag = item?.confidence === 'low' ? LOW : '';
    return (
      flag +
      [
        '// Auto-generated by DesignBridge',
        'export function Button({ variant = "primary", className = "", ...props }) {',
        '  const base =',
        `    "inline-flex items-center justify-center px-4 py-2 rounded-[${p.radius}] text-[${p.fontSize}] font-[${p.fontWeight}] transition-colors";`,
        '  const variants = {',
        `    primary: "bg-[${p.primary}] text-[${p.onPrimary}] hover:opacity-90",`,
        `    secondary: "border border-[${p.border}] text-[${p.text}] hover:bg-[${p.surfaceMuted}]",`,
        `    ghost: "text-[${p.primary}] hover:bg-[${p.surfaceMuted}]",`,
        '  };',
        '  return <button className={[base, variants[variant], className].join(" ")} {...props} />;',
        '}',
        '',
      ].join('\n')
    );
  },
  styleFor(variant, p) {
    const base = {
      display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
      padding: '8px 16px', borderRadius: p.radius, fontSize: p.fontSize,
      fontWeight: Number(p.fontWeight) || 500, border: '1px solid transparent',
      cursor: 'pointer',
    };
    if (variant === 'secondary')
      return { ...base, background: 'transparent', color: p.text, borderColor: p.border };
    if (variant === 'ghost')
      return { ...base, background: 'transparent', color: p.primary };
    return { ...base, background: p.primary, color: p.onPrimary };
  },
  planFor(variant, r) {
    const base = box({ padding: [8, 16, 8, 16], radius: px(r.radius, 6) });
    if (variant === 'secondary')
      return { ...base, stroke: colorRef(r.border), children: [textEl('Button', r, r.text)] };
    if (variant === 'ghost')
      return { ...base, children: [textEl('Button', r, r.primary)] };
    return { ...base, fill: colorRef(r.primary), children: [textEl('Button', r, r.onPrimary)] };
  },
};
