import { LOW_CONFIDENCE_COMMENT as LOW } from './constants.js';
import { colorRef, px, textEl, box } from './planHelpers.js';

export const buttonTemplate = {
  key: 'button',
  label: 'Button',
  variants: ['primary', 'secondary', 'ghost'],
  match: (n) => /butt|btn|cta/.test(n),
  emit(p, item) {
    const flag = item?.confidence === 'low' ? LOW : '';
    const isIcon = /\bicon\b/i.test(item?.name ?? '');
    const variants = [
      '  const variants = {',
      `    primary: "bg-[${p.primary}] text-[${p.onPrimary}] hover:opacity-90",`,
      `    secondary: "border border-[${p.border}] text-[${p.text}] hover:bg-[${p.surfaceMuted}]",`,
      `    ghost: "text-[${p.primary}] hover:bg-[${p.surfaceMuted}]",`,
      '  };',
    ];
    const lines = isIcon
      ? [
          '// Auto-generated by DesignBridge',
          'export function IconButton({ variant = "primary", "aria-label": ariaLabel = "Aktion", className = "", ...props }) {',
          '  const base =',
          `    "inline-flex items-center justify-center h-9 w-9 rounded-[${p.radius}] transition-colors";`,
          ...variants,
          '  return (',
          '    <button aria-label={ariaLabel} className={[base, variants[variant], className].join(" ")} {...props}>',
          '      <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 5v14M5 12h14" /></svg>',
          '    </button>',
          '  );',
          '}',
          '',
        ]
      : [
          '// Auto-generated by DesignBridge',
          'export function Button({ variant = "primary", className = "", ...props }) {',
          '  const base =',
          `    "inline-flex items-center justify-center px-4 py-2 rounded-[${p.radius}] text-[${p.fontSize}] font-[${p.fontWeight}] transition-colors";`,
          ...variants,
          '  return <button className={[base, variants[variant], className].join(" ")} {...props} />;',
          '}',
          '',
        ];
    return flag + lines.join('\n');
  },
  styleFor(variant, p) {
    const base = {
      display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
      padding: '8px 16px', borderRadius: p.radius, fontSize: p.fontSize,
      fontWeight: Number(p.fontWeight) || 500, border: '1px solid transparent',
      cursor: 'pointer',
    };
    if (variant === 'secondary')
      return { ...base, background: 'transparent', color: p.text, borderColor: p.border };
    if (variant === 'ghost')
      return { ...base, background: 'transparent', color: p.primary };
    return { ...base, background: p.primary, color: p.onPrimary };
  },
  planFor(variant, r, item) {
    // Icon-Fall wie in emit(): quadratischer Button mit Plus-Icon statt Text-Label
    // (Fix 14.07. — vorher kam Icon Button in Figma als identische Text-Kopie an).
    const isIcon = /\bicon\b/i.test(item?.name ?? '');
    const iconSvg = (slot) => ({
      type: 'svg',
      markup: `<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="${slot.value}" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 5v14M5 12h14"/></svg>`,
    });
    const base = box({ padding: isIcon ? [10, 10, 10, 10] : [8, 16, 8, 16], radius: px(r.radius, 6) });
    const content = (slot) => (isIcon ? iconSvg(slot) : textEl('Button', r, slot));
    if (variant === 'secondary')
      return { ...base, stroke: colorRef(r.border), children: [content(r.text)] };
    if (variant === 'ghost')
      return { ...base, children: [content(r.primary)] };
    return { ...base, fill: colorRef(r.primary), children: [content(r.onPrimary)] };
  },
};
