import { LOW_CONFIDENCE_COMMENT as LOW } from './constants.js';

export const cardTemplate = {
  key: 'card',
  label: 'Card',
  variants: ['default'],
  match: (n) => /card|tile|panel/.test(n),
  emit(p, item) {
    const flag = item?.confidence === 'low' ? LOW : '';
    return (
      flag +
      [
        '// Auto-generated by DesignBridge',
        'export function Card({ className = "", ...props }) {',
        '  return (',
        `    <div className={["bg-[${p.surface}] border border-[${p.border}] rounded-[${p.radius}] p-4", className].join(" ")} {...props} />`,
        '  );',
        '}',
        '',
      ].join('\n')
    );
  },
  styleFor(_variant, p) {
    return {
      background: p.surface, border: `1px solid ${p.border}`,
      borderRadius: p.radius, padding: '16px', color: p.text,
      fontSize: p.fontSize, minWidth: '160px',
    };
  },
};
