import { LOW_CONFIDENCE_COMMENT as LOW } from './constants.js';
import { colorRef, px, textEl, box } from './planHelpers.js';

export const cardTemplate = {
  key: 'card',
  label: 'Card',
  variants: ['default'],
  match: (n) => /card|tile|panel/.test(n),
  emit(p, item) {
    const flag = item?.confidence === 'low' ? LOW : '';
    return (
      flag +
      [
        '// Auto-generated by DesignBridge',
        'export function Card({ className = "", ...props }) {',
        '  return (',
        `    <div className={["bg-[${p.surface}] border border-[${p.border}] rounded-[${p.radius}] p-4", className].join(" ")} {...props} />`,
        '  );',
        '}',
        '',
      ].join('\n')
    );
  },
  styleFor(_variant, p) {
    return {
      background: p.surface, border: `1px solid ${p.border}`,
      borderRadius: p.radius, padding: '16px', color: p.text,
      fontSize: p.fontSize, minWidth: '160px',
    };
  },
  planFor(_variant, r) {
    return box({
      layout: 'column', padding: [16, 16, 16, 16], radius: px(r.radius, 6),
      fill: colorRef(r.surface), stroke: colorRef(r.border),
      children: [
        textEl('Card-Titel', r, r.text, { fontWeight: 600 }),
        textEl('Beschreibender Text der Karte.', r, r.text),
      ],
    });
  },
};
