import { LOW_CONFIDENCE_COMMENT as LOW } from './constants.js';

export const inputTemplate = {
  key: 'input',
  label: 'Input',
  variants: ['default', 'disabled'],
  match: (n) => /input|field|textbox|text box|form field/.test(n),
  emit(p, item) {
    const flag = item?.confidence === 'low' ? LOW : '';
    return (
      flag +
      [
        '// Auto-generated by DesignBridge',
        'export function Input({ className = "", ...props }) {',
        '  return (',
        `    <input className={["w-full px-3 py-2 bg-[${p.surface}] border border-[${p.border}] rounded-[${p.radius}] text-[${p.fontSize}] disabled:opacity-50", className].join(" ")} {...props} />`,
        '  );',
        '}',
        '',
      ].join('\n')
    );
  },
  styleFor(variant, p) {
    return {
      width: '100%', padding: '8px 12px', background: p.surface,
      border: `1px solid ${p.border}`, borderRadius: p.radius,
      fontSize: p.fontSize, color: p.text,
      opacity: variant === 'disabled' ? 0.5 : 1,
    };
  },
};
